Config = {}

Config["MDTCommand"] = "mdt"

Config["PoliceJobs"] = {
    "police",
    "sheriff",
    "state"
}

Config["EMSJobs"] = {
    "ems"
}

Config["PoliceRosterLink"] = "https://docs.google.com/spreadsheets/d/e/2PACX-1vTLzt7g91taLqRMW3weARAE_odQdATO-uLidLCejHXig2CEOV5za5WKSSu2kLuN8U-5FglSI2TW8s1_/pubhtml?gid=0&amp;single=true&amp;widget=true&amp;headers=false%22%3E"

Config["EMSRosterLink"] = ""

Config["PublicRecords"] = {
    ['Coords'] = vector3(236.35, -409.44, 47.92),
    ['AllowImageChange'] = false
}

Config["SQLWrapper"] = "ghmattimysql"

Config["CoreSettings"]  = {
    ["Core"] = "rrpbase",
    ["RRPBase"] = {
        ["CoreName"] = "drp-base"
    }
}

Config['OffensesTitels'] = {
        [1] = ''
}

Config["Offenses"] = {
    [1] = {
        [0] = {title = 'Act of Torture', class = 'Felony', id = '0', months = 18, fine = 1350, color = 'orange'},
        [1] = {title = 'Assault & Battery', class = 'Misdemeanor', id = '1', months = 11, fine = 825, color = 'orange'},
        [2] = {title = 'Accomplice of Assault & Battery', class = 'Misdemeanor', id = '2', months = 11, fine = 825, color = 'orange'},
        [3] = {title = 'Accessory of Assault & Battery', class = 'Misdemeanor', id = '3', months = 9, fine = 660, color = 'orange'},
        [4] = {title = 'Unlawful', class = 'Imprisonment', id = '4', months = Felony, fine = 11825, color = 'orange'},
        [5] = {title = 'Accomplice of Unlawful Imprisonment', class = 'Felony', id = '5', months = 11, fine = 825, color = 'orange'},
        [6] = {title = 'Accessory of Unlawful Imprisonment', class = 'Felony', id = '6', months = 9, fine = 660, color = 'orange'},
        [7] = {title = 'Kidnapping', class = 'Felony', id = '7', months = 14, fine = 1050, color = 'orange'},
        [8] = {title = 'Accomplice of Kidnapping', class = 'Kidnapping', id = '8', months = Felony, fine = 1050, color = 'orange'},
        [9] = {title = 'Accessory of Kidnapping', class = 'Kidnapping', id = '9', months = Felony, fine = 840, color = 'orange'},
        [10] = {title = 'Kidnapping a Government Employee', class = 'Felony', id = '10', months = 25, fine = 1875, color = 'orange'},
        [11] = {title = 'Accomplice to Kidnapping of a Government Employee', class = 'Felony', id = '11', months = 25, fine = 1875, color = 'orange'},
        [12] = {title = 'Accessory to Kidnapping of a Government Employee', class = 'Felony', id = '12', months = 20, fine = 1500, color = 'orange'},
        [13] = {title = 'Assault with a Deadly Weapon', class = 'Felony', id = '13', months = 21, fine = 1575, color = 'orange'},
        [14] = {title = 'Accomplice of Assault with a Deadly Weapon', class = 'Felony', id = '14', months = 21, fine = 1575, color = 'orange'},
        [15] = {title = 'Accessory of Assault with a Deadly Weapon', class = 'Felony', id = '15', months = 17, fine = 1260, color = 'orange'},
        [16] = {title = 'Manslaughter', class = 'Felony', id = '16', months = 150, fine = 11250, color = 'orange'},
        [17] = {title = 'Accomplice of Manslaughter', class = 'Felony', id = '17', months = 150, fine = 11250, color = 'orange'},
        [18] = {title = 'Accessory of Manslaughter', class = 'Felony', id = '18', months = 120, fine = 9000, color = 'orange'},
        [19] = {title = 'Attempted 2nd Degree Murder', class = 'Felony', id = '19', months = 25, fine = 1875, color = 'orange'},
        [20] = {title = 'Accomplice of Attempted 2nd Degree Murder', class = 'Felony', id = '20', months = 25, fine = 1875, color = 'orange'},
        [21] = {title = 'Accessory of Attempted 2nd Degree Murder', class = 'Felony', id = '21', months = 20, fine = 1500, color = 'orange'},
        [22] = {title = '2nd Degree Murder', class = 'Felony', id = '22', months = 300, fine = 22500, color = 'orange'},
        [23] = {title = 'Accomplice of 2nd Degree Murder', class = 'Felony', id = '23', months = 300, fine = 22500, color = 'orange'},
        [24] = {title = 'Accessory of 2nd Degree Murder', class = 'Felony', id = '24', months = 240, fine = 18000, color = 'orange'},
        [25] = {title = 'Attempted 1st Degree Murder', class = 'Felony', id = '25', months = 35, fine = 2625, color = 'orange'},
        [26] = {title = 'Accomplice of Attempted 1st Degree', class = 'Murder', id = '26', months = Felony, fine = 2625, color = 'orange'},
        [27] = {title = 'Accessory of Attempted 1st Degree', class = 'Murder', id = '27', months = Felony, fine = 2100, color = 'orange'},
        [28] = {title = '1st Degree Murder', class = 'Felony', id = '28', months = 0, fine = 0, color = 'orange'},
        [29] = {title = 'Accomplice of 1st Degree Murder', class = 'Felony', id = '29', months = 0, fine = 0, color = 'orange'},
        [30] = {title = 'Accessory of 1st Degree Murder', class = 'Felony', id = '30', months = 0, fine = 0, color = 'orange'},
        [31] = {title = 'Criminal Threats', class = 'Misdemeanor', id = '31', months = 14, fine = 1050, color = 'orange'},
        [32] = {title = 'Accomplice of Criminal Threats', class = 'Threats', id = '32', months = Misdemeanor, fine = 1050, color = 'orange'},
        [33] = {title = 'Accessory of Criminal Threats', class = 'Threats', id = '33', months = Misdemeanor, fine = 840, color = 'orange'},
        [34] = {title = 'Attempted Murder of a Government Employee', class = 'Felony', id = '34', months = 45, fine = 3375, color = 'orange'},
        [35] = {title = 'Accomplice of Attempted Murder of a Government Employee', class = 'Felony', id = '35', months = 45, fine = 3375, color = 'orange'},
        [36] = {title = 'Accessory of Attempted Murder of a Government Employss', class = 'Felony', id = '36', months = 36, fine = 2700, color = 'orange'},
        [37] = {title = 'Murder of a Government Employee', class = 'Felony', id = '37', months = 0, fine = 0, color = 'orange'},
        [38] = {title = 'Accomplice of Murder of a Governement Employee', class = 'Felony', id = '38', months = 0, fine = 0, color = 'orange'},
        [39] = {title = 'Accessory of Murder of a Governement Employee', class = 'Felony', id = '39', months = 0, fine = 0, color = 'orange'},
        [40] = {title = 'Gang Related Shooting', class = 'Felony', id = '40', months = 75, fine = 500, color = 'orange'},
        [41] = {title = 'Accomplice of a Gang Related Shooting', class = 'Felony', id = '41', months = 75, fine = 500, color = 'orange'},
        [42] = {title = 'Accessory of a Gang Related Shooting', class = 'Felony', id = '42', months = 60, fine = 400, color = 'orange'},
        [43] = {title = 'Reckless Endangerment', class = 'Felony', id = '43', months = 11, fine = 825, color = 'orange'},
        [44] = {title = 'Accomplice of Reckless Endangerment', class = 'Felony', id = '44', months = 11, fine = 825, color = 'orange'},
        [45] = {title = 'Accessory of Reckless Endangerment', class = 'Felony', id = '45', months = 9, fine = 660, color = 'orange'},
        [46] = {title = 'Brandishing of a Firearm', class = 'Misdemeanor', id = '46', months = 7, fine = 525, color = 'orange'},
        [47] = {title = 'Forcers Law', class = 'Felony', id = '47', months = 0, fine = HU, color = 'orange'},
        [48] = {title = 'Petty Theft', class = 'Infraction', id = '48', months = 0, fine = 250, color = 'orange'},
        [49] = {title = 'Accomplice to Petty Theft', class = 'Infraction', id = '49', months = 0, fine = 250, color = 'orange'},
        [50] = {title = 'Accessory to Petty Theft', class = 'Infraction', id = '50', months = 0, fine = 200, color = 'orange'},
        [51] = {title = 'Grand Theft', class = 'Misdemeanor', id = '51', months = 5, fine = 375, color = 'orange'},
        [52] = {title = 'Accomplice of Grand Theft', class = 'Misdemeanor', id = '52', months = 5, fine = 375, color = 'orange'},
        [53] = {title = 'Accessory of Grand Theft', class = 'Misdemeanor', id = '53', months = 4, fine = 300, color = 'orange'},
        [54] = {title = 'Joyriding', class = 'Misdemeanor', id = '54', months = 7, fine = 525, color = 'orange'},
        [55] = {title = 'Accomplice to Joyriding', class = 'Misdemeanor', id = '55', months = 7, fine = 525, color = 'orange'},
        [56] = {title = 'Accessory to Joyriding', class = 'Misdemeanor', id = '56', months = 6, fine = 420, color = 'orange'},
        [57] = {title = 'Grand Theft Auto', class = 'Felony', id = '57', months = 14, fine = 1050, color = 'orange'},
        [58] = {title = 'Accomplice to Grand Theft Auto', class = 'Felony', id = '58', months = 14, fine = 1050, color = 'orange'},
        [59] = {title = 'Accessory to Grand Theft Auto', class = 'Felony', id = '59', months = 12, fine = 840, color = 'orange'},
        [60] = {title = 'Tampering with a Vehicle', class = 'Misdemeanor', id = '60', months = 7, fine = 525, color = 'orange'},
        [61] = {title = 'Accomplice to Tampering with a Vehicle', class = 'Misdemeanor', id = '61', months = 7, fine = 525, color = 'orange'},
        [62] = {title = 'Accessory to Tampering with a Vehicle', class = 'Misdemeanor', id = '62', months = 6, fine = 420, color = 'orange'},
        [63] = {title = 'Receiving Stolen Property in the Third Degree', class = 'Misdemeanor', id = '63', months = 7, fine = 525, color = 'orange'},
        [64] = {title = 'Receiving Stolen Property in the Second Degree', class = 'Misdemeanor', id = '64', months = 12, fine = 900, color = 'orange'},
        [65] = {title = 'Receiving Stolen Property in the First Degree', class = 'Felony', id = '65', months = 14, fine = 1050, color = 'orange'},
        [66] = {title = 'Robbery of a Financial Institution', class = 'Felony', id = '66', months = 60, fine = 6200, color = 'orange'},
        [67] = {title = 'Robbery', class = 'Felony', id = '67', months = 25, fine = 1875, color = 'orange'},
        [68] = {title = 'Accomplice to Robbery', class = 'Felony', id = '68', months = 25, fine = 1875, color = 'orange'},
        [69] = {title = 'Accessory to Robbery', class = 'Felony', id = '69', months = 20, fine = 1500, color = 'orange'},
        [70] = {title = 'First Degree Robbery', class = 'Felony', id = '70', months = 30, fine = 2250, color = 'orange'},
        [71] = {title = 'Accomplice to First Degree Robbery', class = 'Robbery', id = '71', months = Felony, fine = 2250, color = 'orange'},
        [72] = {title = 'Accessory to First Degree Robbery', class = 'Robbery', id = '72', months = Felony, fine = 1800, color = 'orange'},
        [73] = {title = 'Possession of Stolen Goods', class = 'Felony', id = '73', months = 14, fine = 1050, color = 'orange'},
        [74] = {title = 'Possession of a Stolen Identification', class = 'Misdemeanor', id = '74', months = 12, fine = 900, color = 'orange'},
        [75] = {title = 'Grand Larceny', class = 'Felony', id = '75', months = 33, fine = 2750, color = 'orange'},
        [76] = {title = 'Accomplice to Grand Larceny', class = 'Felony', id = '76', months = 33, fine = 2750, color = 'orange'},
        [77] = {title = 'Accessory to Grand Larceny', class = 'Felony', id = '77', months = 28, fine = 2450, color = 'orange'},
        [78] = {title = 'Possession of Dirty Money in the Second Degree', class = 'Misdemeanor', id = '78', months = 12, fine = 900, color = 'orange'},
        [79] = {title = 'Possession of Dirty Money in the First Degree', class = 'Felony', id = '79', months = 21, fine = 1575, color = 'orange'},
        [80] = {title = 'Leaving Without Paying', class = 'Misdemeanor', id = '80', months = 12, fine = 900, color = 'orange'},
        [81] = {title = 'Accomplice to Leaving Without Paying', class = 'Misdemeanor', id = '81', months = 12, fine = 900, color = 'orange'},
        [82] = {title = 'Accessory to Leaving Without Paying', class = 'Misdemeanor', id = '82', months = 10, fine = 720, color = 'orange'},
        [83] = {title = 'Sale of Stolen Goods or Stolen Property', class = 'Misdemeanor', id = '83', months = 22, fine = 1650, color = 'orange'},
        [84] = {title = 'Accomplice to Sale of Stolen Goods or Stolen Property', class = 'Misdemeanor', id = '84', months = 22, fine = 1650, color = 'orange'},
        [85] = {title = 'Accessory to Sale of Stolen Goods or Stolen Property', class = 'Misdemeanor', id = '85', months = 18, fine = 1320, color = 'orange'},
        [86] = {title = 'Theft of a Commercial Aircraft', class = 'Felony', id = '86', months = 23, fine = 1725, color = 'orange'},
        [87] = {title = 'Theft of an Aircraft', class = 'Felony', id = '87', months = 19, fine = 142, color = 'orange'},
        [88] = {title = 'Extortion', class = 'Felony', id = '88', months = 14, fine = 1050, color = 'orange'},
        [89] = {title = 'Accomplice to Extortion', class = 'Felony', id = '89', months = 14, fine = 1050, color = 'orange'},
        [90] = {title = 'Accessory to Extortion', class = 'Felony', id = '90', months = 12, fine = 840, color = 'orange'},
        [91] = {title = 'Fraud', class = 'Felony', id = '91', months = 14, fine = 1050, color = 'orange'},
        [92] = {title = 'Accomplice to Fraud', class = 'Felony', id = '92', months = 14, fine = 1050, color = 'orange'},
        [93] = {title = 'Accessory to Fraud', class = 'Felony', id = '93', months = 12, fine = 840, color = 'orange'},
        [94] = {title = 'Impersonation', class = 'Felony', id = '94', months = 14, fine = 1050, color = 'orange'},
        [95] = {title = 'Accomplice to Impersonation', class = 'Felony', id = '95', months = 14, fine = 1050, color = 'orange'},
        [96] = {title = 'Accessory to Impersonation', class = 'Felony', id = '96', months = 12, fine = 840, color = 'orange'},
        [97] = {title = 'Impersonating a Peace Officer', class = 'Felony', id = '97', months = 21, fine = 1575, color = 'orange'},
        [98] = {title = 'Accomplice to Impersonating a Peace Officer', class = 'Felony', id = '98', months = 21, fine = 1575, color = 'orange'},
        [99] = {title = 'Accessory to Impersonating a Peace Officer', class = 'Felony', id = '99', months = 17, fine = 1260, color = 'orange'},
        [100] = {title = 'Impersonating a Judge', class = 'Felony', id = '100', months = 21, fine = 1575, color = 'orange'},
        [101] = {title = 'Accomplice to Impersonating a Judge', class = 'Felony', id = '101', months = 21, fine = 1575, color = 'orange'},
        [102] = {title = 'Accessory to Impersonating a Judge', class = 'Felony', id = '102', months = 17, fine = 1260, color = 'orange'},
        [103] = {title = 'Vehicle Registration Fraud', class = 'Felony', id = '103', months = 21, fine = 1575, color = 'orange'},
        [104] = {title = 'Identity Theft', class = 'Felony', id = '104', months = 21, fine = 1575, color = 'orange'},
        [105] = {title = 'Accomplice to Identity Theft', class = 'Felony', id = '105', months = 21, fine = 1575, color = 'orange'},
        [106] = {title = 'Accessory to Identity Theft', class = 'Felony', id = '106', months = 17, fine = 1260, color = 'orange'},
        [107] = {title = 'Impersonating EMS', class = 'Felony', id = '107', months = 21, fine = 1575, color = 'orange'},
        [108] = {title = 'Accomplice to Impersonating EMS', class = 'Felony', id = '108', months = 21, fine = 1575, color = 'orange'},
        [109] = {title = 'Accessory to Impersonating EMS', class = 'Felony', id = '109', months = 17, fine = 1260, color = 'orange'},
        [110] = {title = 'Possession of Band of Notes and Small Band of Notes', class = 'Misdemeanor', id = '110', months = 0, fine = 0, color = 'orange'},
        [111] = {title = 'Possession of a Tampered Firearm', class = 'Felony', id = '111', months = 30, fine = 3750, color = 'orange'},
        [112] = {title = 'Witness Tampering', class = 'Felony', id = '112', months = 0, fine = 0, color = 'orange'},
        [113] = {title = 'Accomplice of Witness Tampering', class = 'Felony', id = '113', months = 0, fine = 0, color = 'orange'},
        [114] = {title = 'Accessory of Witness Tampering', class = 'Felony', id = '114', months = 0, fine = 0, color = 'orange'},
        [115] = {title = 'Money Laundering', class = 'Felony', id = '115', months = 30, fine = 2250, color = 'orange'},
        [116] = {title = 'Accessory to Money Laundering', class = 'Felony', id = '116', months = 5, fine = 50, color = 'orange'},
        [117] = {title = 'Embezzlement', class = 'Felony', id = '117', months = 50, fine = 3750, color = 'orange'},
        [118] = {title = 'Accomplice to Embezzlement', class = 'Felony', id = '118', months = 50, fine = 3750, color = 'orange'},
        [119] = {title = 'Accessory to Embezzlement', class = 'Felony', id = '119', months = 17, fine = 420, color = 'orange'},
        [120] = {title = 'Misdemeanor Tax Evasion', class = 'Misdemeanor', id = '120', months = 0, fine = 0, color = 'orange'},
        [121] = {title = 'Felony Tax Evasion', class = 'Felony', id = '121', months = 0, fine = 0, color = 'orange'},
        [122] = {title = 'Burglary', class = 'Felony', id = '122', months = 12, fine = 900, color = 'orange'},
        [123] = {title = 'Accomplice to Burglary', class = 'Felony', id = '123', months = 12, fine = 900, color = 'orange'},
        [124] = {title = 'Accessory to Burglary', class = 'Felony', id = '124', months = 10, fine = 720, color = 'orange'},
        [125] = {title = 'Felony Trespassing', class = 'Felony', id = '125', months = 12, fine = 900, color = 'orange'},
        [126] = {title = 'Accomplice to Trespassing', class = 'Felony', id = '126', months = 12, fine = 900, color = 'orange'},
        [127] = {title = 'Accessory to Trespassing', class = 'Felony', id = '127', months = 10, fine = 720, color = 'orange'},
        [128] = {title = 'Trespassing', class = 'Misdemeanor', id = '128', months = 5, fine = 375, color = 'orange'},
        [129] = {title = 'Accomplice to Trespassing', class = 'Misdemeanor', id = '129', months = 5, fine = 375, color = 'orange'},
        [130] = {title = 'Accessory to Trespassing', class = 'Misdemeanor', id = '130', months = 4, fine = 300, color = 'orange'},
        [131] = {title = 'Arson', class = 'Felony', id = '131', months = 21, fine = 1575, color = 'orange'},
        [132] = {title = 'Accomplice to Arson', class = 'Felony', id = '132', months = 21, fine = 1575, color = 'orange'},
        [133] = {title = 'Accessory to Arson', class = 'Felony', id = '133', months = 17, fine = 12, color = 'orange'},
        [134] = {title = 'Bribery', class = 'Felony', id = '134', months = 12, fine = 900, color = 'orange'},
        [135] = {title = 'Accomplice to Bribery', class = 'Felony', id = '135', months = 12, fine = 900, color = 'orange'},
        [136] = {title = 'Accessory to Bribery', class = 'Felony', id = '136', months = 10, fine = 720, color = 'orange'},
        [137] = {title = 'Contempt of Court', class = 'Misdemeanor', id = '137', months = 0, fine = 0, color = 'orange'},
        [138] = {title = 'Accomplice to Contempt of Court', class = 'Misdemeanor', id = '138', months = 0, fine = 0, color = 'orange'},
        [139] = {title = 'Accessory to Contempt of Court', class = 'Misdemeanor', id = '139', months = 0, fine = 0, color = 'orange'},
        [140] = {title = 'Escaping Custody', class = 'Felony', id = '140', months = 14, fine = 1050, color = 'orange'},
        [141] = {title = 'Accomplice to Escaping Custody', class = 'Felony', id = '141', months = 14, fine = 1050, color = 'orange'},
        [142] = {title = 'Accessory to Escaping Custody', class = 'Felony', id = '142', months = 12, fine = 800, color = 'orange'},
        [143] = {title = 'Prison Break', class = 'Felony', id = '143', months = 40, fine = 3000, color = 'orange'},
        [144] = {title = 'Accomplice to Prison Break', class = 'Felony', id = '144', months = 40, fine = 3000, color = 'orange'},
        [145] = {title = 'Accessory to Prison Break', class = 'Felony', id = '145', months = 32, fine = 2400, color = 'orange'},
        [146] = {title = 'Perjury', class = 'Felony', id = '146', months = 21, fine = 1575, color = 'orange'},
        [147] = {title = 'Accomplice to Perjury', class = 'Felony', id = '147', months = 21, fine = 1575, color = 'orange'},
        [148] = {title = 'Accessory to Perjury', class = 'Felony', id = '148', months = 17, fine = 1260, color = 'orange'},
        [149] = {title = 'Violating a Court Order', class = 'Felony', id = '149', months = 28, fine = 2100, color = 'orange'},
        [150] = {title = 'Accomplice to Violating a Court Order', class = 'Felony', id = '150', months = 28, fine = 2100, color = 'orange'},
        [151] = {title = 'Accessory to Violating a Court Order', class = 'Felony', id = '151', months = 23, fine = 1680, color = 'orange'},
        [152] = {title = 'Failure to Appear', class = 'Misdemeanor', id = '152', months = 0, fine = 0, color = 'orange'},
        [153] = {title = 'Accomplice to Failure to Appear', class = 'Misdemeanor', id = '153', months = 0, fine = 0, color = 'orange'},
        [154] = {title = 'Accessory to Failure to Appear', class = 'Misdemeanor', id = '154', months = 0, fine = 0, color = 'orange'},
        [155] = {title = 'Unauthorized Practice of Law', class = 'Misdemeanor', id = '155', months = 5, fine = 375, color = 'orange'},
        [156] = {title = 'Accomplice to Unauthorized Practice of Law', class = 'Misdemeanor', id = '156', months = 5, fine = 375, color = 'orange'},
        [157] = {title = 'Accessory to Unauthorized Practice of Law', class = 'Misdemeanor', id = '157', months = 4, fine = 300, color = 'orange'},
        [158] = {title = 'Conspiracy', class = 'Misdemeanor', id = '158', months = 7, fine = 525, color = 'orange'},
        [159] = {title = 'Accomplice to Conspiracy', class = 'Misdemeanor', id = '159', months = 7, fine = 525, color = 'orange'},
        [160] = {title = 'Accessory to Conspiracy', class = 'Misdemeanor', id = '160', months = 6, fine = 420, color = 'orange'},
        [161] = {title = 'Attempted Prison Break', class = 'Felony', id = '161', months = 28, fine = 2100, color = 'orange'},
        [162] = {title = 'Accomplice to Attempted Prison Break', class = 'Felony', id = '162', months = 28, fine = 2100, color = 'orange'},
        [163] = {title = 'Accessory to Attempted Prison Break', class = 'Felony', id = '163', months = 23, fine = 1600, color = 'orange'},
        [164] = {title = 'Parole Violation', class = 'Felony', id = '164', months = 0, fine = 0, color = 'orange'},
        [165] = {title = 'Misuse of a 911 System', class = 'Misdemeanor', id = '165', months = 7, fine = 525, color = 'orange'},
        [166] = {title = 'Introducing Contraband Into a Government Facility', class = 'Felony', id = '166', months = 20, fine = 1500, color = 'orange'},
        [167] = {title = 'Accomplice to Introducing Contraband Into a Government Facility', class = 'Felony', id = '167', months = 20, fine = 1500, color = 'orange'},
        [168] = {title = 'Accessory to Introducing Contraband Into a Government Facility', class = 'Felony', id = '168', months = 16, fine = 1200, color = 'orange'},
        [169] = {title = 'Concealing an Escaped Prisoner (Pattys Law)', class = 'Felony', id = '169', months = 0, fine = 0, color = 'orange'},
        [170] = {title = 'Disobeying a Peace Officer', class = 'Misdemeanor', id = '170', months = 7, fine = 525, color = 'orange'},
        [171] = {title = 'Accomplice to Disobeying a Peace Officer', class = 'Misdemeanor', id = '171', months = 7, fine = 525, color = 'orange'},
        [172] = {title = 'Accessory to Disobeying a Peace Officer', class = 'Misdemeanor', id = '172', months = 6, fine = 420, color = 'orange'},
        [173] = {title = 'Disorderly Conduct', class = 'Misdemeanor', id = '173', months = 5, fine = 3, color = 'orange'},
        [174] = {title = 'Accomplice to Disorderly Conduct', class = 'Misdemeanor', id = '174', months = 5, fine = 3, color = 'orange'},
        [175] = {title = 'Accessory to Disorderly Conduct', class = 'Misdemeanor', id = '175', months = 4, fine = 3, color = 'orange'},
        [176] = {title = 'Disturbing the Peace', class = 'Misdemeanor', id = '176', months = 5, fine = 375, color = 'orange'},
        [177] = {title = 'Accomplice to Disturbing the Peace', class = 'Misdemeanor', id = '177', months = 5, fine = 375, color = 'orange'},
        [178] = {title = 'Accessory to Disturbing the Peace', class = 'Misdemeanor', id = '178', months = 4, fine = 300, color = 'orange'},
        [179] = {title = 'False Reporting', class = 'Misdemeanor', id = '179', months = 7, fine = 525, color = 'orange'},
        [180] = {title = 'Accomplice to False Reporting', class = 'Misdemeanor', id = '180', months = 7, fine = 525, color = 'orange'},
        [181] = {title = 'Accessory to False Reporting', class = 'Misdemeanor', id = '181', months = 6, fine = 420, color = 'orange'},
        [182] = {title = 'Harassment', class = 'Misdemeanor', id = '182', months = 7, fine = 525, color = 'orange'},
        [183] = {title = 'Accomplice to Harassment', class = 'Misdemeanor', id = '183', months = 7, fine = 525, color = 'orange'},
        [184] = {title = 'Accessory to Harassment', class = 'Misdemeanor', id = '184', months = 6, fine = 420, color = 'orange'},
        [185] = {title = 'Misdemeanor Obstruction of Justice', class = 'Misdemeanor', id = '185', months = 12, fine = 900, color = 'orange'},
        [186] = {title = 'Accomplice to Misdemeanor Obstruction of Justice', class = 'Misdemeanor', id = '186', months = 12, fine = 900, color = 'orange'},
        [187] = {title = 'Accessory to Misdemeanor Obstruction of Justice', class = 'Misdemeanor', id = '187', months = 10, fine = 720, color = 'orange'},
        [188] = {title = 'Riot', class = 'Felony', id = '188', months = 18, fine = 1350, color = 'orange'},
        [189] = {title = 'Accomplice to Riot', class = 'Felony', id = '189', months = 18, fine = 1350, color = 'orange'},
        [190] = {title = 'Accessory to Riot', class = 'Felony', id = '190', months = 15, fine = 1080, color = 'orange'},
        [191] = {title = 'Vandalism', class = 'Infraction', id = '191', months = 0, fine = 250, color = 'orange'},
        [192] = {title = 'Accomplice to Vandalism', class = 'Infraction', id = '192', months = 0, fine = 250, color = 'orange'},
        [193] = {title = 'Accessory to Vandalism', class = 'Infraction', id = '193', months = 0, fine = 200, color = 'orange'},
        [194] = {title = 'Tampering of Evidence', class = 'Misdemeanor', id = '194', months = 7, fine = 525, color = 'orange'},
        [195] = {title = 'Accomplice to Tampering of Evidence', class = 'Misdemeanor', id = '195', months = 7, fine = 525, color = 'orange'},
        [196] = {title = 'Accessory to Tampering of Evidence', class = 'Misdemeanor', id = '196', months = 6, fine = 420, color = 'orange'},
        [197] = {title = 'Vandalism of Government Property', class = 'Misdemeanor', id = '197', months = 5, fine = 375, color = 'orange'},
        [198] = {title = 'Accomplice to Vandalism of Government Property', class = 'Misdemeanor', id = '198', months = 5, fine = 375, color = 'orange'},
        [199] = {title = 'Accessory to Vandalism of Government Property', class = 'Misdemeanor', id = '199', months = 4, fine = 300, color = 'orange'},
        [200] = {title = 'Stalking', class = 'Misdemeanor', id = '200', months = 7, fine = 250, color = 'orange'},
        [201] = {title = 'Accomplice to Stalking', class = 'Misdemeanor', id = '201', months = 7, fine = 250, color = 'orange'},
        [202] = {title = 'Accessory Stalking', class = 'Misdemeanor', id = '202', months = 6, fine = 200, color = 'orange'},
        [203] = {title = 'Misdemeanor Animal Cruelty', class = 'Misdemeanor', id = '203', months = 7, fine = 525, color = 'orange'},
        [204] = {title = 'Accomplice to Animal Cruelty', class = 'Misdemeanor', id = '204', months = 7, fine = 525, color = 'orange'},
        [205] = {title = 'Accessory to Animal Cruelty', class = 'Misdemeanor', id = '205', months = 6, fine = 420, color = 'orange'},
        [206] = {title = 'Felony Animal Cruelty', class = 'Felony', id = '206', months = 18, fine = 1350, color = 'orange'},
        [207] = {title = 'Accomplice to FelIony Animal Cruelty', class = 'Felony', id = '207', months = 18, fine = 1350, color = 'orange'},
        [208] = {title = 'Accessory to FelIony Animal Cruelty', class = 'Felony', id = '208', months = 15, fine = 1125, color = 'orange'},
        [209] = {title = 'Disruption of a Public Utility', class = 'Felony', id = '209', months = 28, fine = 2100, color = 'orange'},
        [210] = {title = 'Accomplice to Disruption of a Public Utility', class = 'Felony', id = '210', months = 28, fine = 2100, color = 'orange'},
        [211] = {title = 'Accessory to Disruption of a Public Utility', class = 'Felony', id = '211', months = 23, fine = 1680, color = 'orange'},
        [212] = {title = 'Felony Obstruction of Justice', class = 'Felony', id = '212', months = 24, fine = 1800, color = 'orange'},
        [213] = {title = 'Accomplice to FelIony Obstruction of Justice', class = 'Felony', id = '213', months = 24, fine = 1800, color = 'orange'},
        [214] = {title = 'Accessory to FelIony Obstruction of Justice', class = 'Felony', id = '214', months = 20, fine = 14, color = 'orange'},
        [215] = {title = 'Misdemeanor Possession of Thermite Charges', class = 'Misdemeanor', id = '215', months = 14, fine = 1500, color = 'orange'},
        [216] = {title = 'Felony Possession of Thermite Charges', class = 'Felony', id = '216', months = 22, fine = 2250, color = 'orange'},
        [217] = {title = 'Misdemeanor Possession of Crack', class = 'Misdemeanor', id = '217', months = 7, fine = 525, color = 'orange'},
        [218] = {title = 'Misdemeanor Possession of Cocaine', class = 'Misdemeanor', id = '218', months = 7, fine = 525, color = 'orange'},
        [219] = {title = 'Misdemeanor Possession of Marijuana', class = 'Misdemeanor', id = '219', months = 5, fine = 375, color = 'orange'},
        [220] = {title = 'Misdemeanor Possession of Ketamine', class = 'Misdemeanor', id = '220', months = 7, fine = 525, color = 'orange'},
        [221] = {title = 'Possession of Unknown Prescription Medication', class = 'Misdemeanor', id = '221', months = 10, fine = 975, color = 'orange'},
        [222] = {title = 'Misdemeanor Possession of Controlled Dangerous Substance OXY / METH', class = 'Misdemeanor', id = '222', months = 7, fine = 525, color = 'orange'},
        [223] = {title = 'Sale of Drugs', class = 'Felony', id = '223', months = 25, fine = 1875, color = 'orange'},
        [224] = {title = 'Accomplice to Sale of Drugs', class = 'Felony', id = '224', months = 25, fine = 1875, color = 'orange'},
        [225] = {title = 'Accessory to Sale of Drugs', class = 'Felony', id = '225', months = 20, fine = 1500, color = 'orange'},
        [226] = {title = 'Felony Possession of Marijuana', class = 'Felony', id = '226', months = 25, fine = 1875, color = 'orange'},
        [227] = {title = 'Felony Possession of Ketamine', class = 'Felony', id = '227', months = 25, fine = 1875, color = 'orange'},
        [228] = {title = 'Felony Possession of Cocaine', class = 'Felony', id = '228', months = 25, fine = 1875, color = 'orange'},
        [229] = {title = 'Felony Possession of Crack Cocaine', class = 'Felony', id = '229', months = 25, fine = 1875, color = 'orange'},
        [230] = {title = 'Felony Possession of a Controlled Dangerous Substance OXY / METH', class = 'Felony', id = '230', months = 25, fine = 1875, color = 'orange'},
        [231] = {title = 'Possession of Unknown Prescription Medication', class = 'Felony', id = '231', months = 25, fine = 1875, color = 'orange'},
        [232] = {title = 'Possession of Drug Paraphernalia', class = 'Misdemeanor', id = '232', months = 5, fine = 375, color = 'orange'},
        [233] = {title = 'Felony Possession with intent to Distribute', class = 'Felony', id = '233', months = 150, fine = 12250, color = 'orange'},
        [234] = {title = 'Cultivation of Marijuana', class = 'Felony', id = '234', months = 25, fine = 1875, color = 'orange'},
        [235] = {title = 'Accomplice to Cultivation of Marijuana', class = 'Felony', id = '235', months = 25, fine = 1875, color = 'orange'},
        [236] = {title = 'Accessory to Cultivation of Marijuana', class = 'Felony', id = '236', months = 20, fine = 1500, color = 'orange'},
        [237] = {title = 'Littering', class = 'Infraction', id = '237', months = 0, fine = 250, color = 'orange'},
        [238] = {title = 'Accomplish to Littering', class = 'Infraction', id = '238', months = 0, fine = 250, color = 'orange'},
        [239] = {title = 'Accessory to Littering', class = 'Infraction', id = '239', months = 0, fine = 200, color = 'orange'},
        [240] = {title = 'Public Intoxication', class = 'Infraction', id = '240', months = 0, fine = 150, color = 'orange'},
        [241] = {title = 'Public Indecency', class = 'Misdemeanor', id = '241', months = 7, fine = 525, color = 'orange'},
        [242] = {title = 'Desecration of a Human Corpse', class = 'Felony', id = '242', months = 18, fine = 1350, color = 'orange'},
        [243] = {title = 'Accomplice to Desecration of a Human Corpse', class = 'Felony', id = '243', months = 18, fine = 1350, color = 'orange'},
        [244] = {title = 'Accessory to Desecration of a Human Corpse', class = 'Felony', id = '244', months = 15, fine = 1080, color = 'orange'},
        [245] = {title = 'Practicing Medicine Without a License', class = 'Misdemeanor', id = '245', months = 12, fine = 1125, color = 'orange'},
        [246] = {title = 'Accomplice to Practicing Medicine Without a License', class = 'Misdemeanor', id = '246', months = 12, fine = 1125, color = 'orange'},
        [247] = {title = 'Accessory to Practicing Medicine Without a License', class = 'Misdemeanor', id = '247', months = 10, fine = 900, color = 'orange'},
        [248] = {title = 'Misdemeanor Possession of LSD tabs', class = 'Misdemeanor', id = '248', months = 7, fine = 525, color = 'orange'},
        [249] = {title = 'Felony Possession of LSD Tabs', class = 'Felony', id = '249', months = 25, fine = 1875, color = 'orange'},
        [250] = {title = 'Illegal Exhumation', class = 'Felony', id = '250', months = 1440, fine = 0, color = 'orange'},
        [251] = {title = 'Accomplice to Illegal Exhumation Felony', class = '1440', id = '251', months = 0, fine = 0, color = 'orange'},
        [252] = {title = 'Accessory to Illegal Exhumation Felony', class = '1440', id = '252', months = 0, fine = 0, color = 'orange'},
        [253] = {title = 'Drug Trafficking Felony', class = '1440', id = '253', months = 0, fine = 0, color = 'orange'},
        [254] = {title = 'Accomplice to Drug Trafficking Felony', class = '1440', id = '254', months = 0, fine = 0, color = 'orange'},
        [255] = {title = 'Accessory to Drug Trafficking Felony', class = '1440', id = '255', months = 0, fine = 0, color = 'orange'},
        [256] = {title = 'Human Trafficking Felony', class = '1440', id = '256', months = 1440, fine = 0, color = 'orange'},
        [257] = {title = 'Accomplice to Human Trafficking', class = 'Felony', id = '257', months = 1440, fine = 1440, color = 'orange'},
        [258] = {title = 'Accessory to Human Trafficking', class = 'Felony', id = '258', months = 1440, fine = 1440, color = 'orange'},
        [259] = {title = 'Prostitution', class = 'Felony', id = '259', months = 70, fine = 5000, color = 'orange'},
        [260] = {title = 'Accomplice to Prostitution', class = 'Felony', id = '260', months = 70, fine = 5000, color = 'orange'},
        [261] = {title = 'Accessory to Prostitution', class = 'Felony', id = '261', months = 56, fine = 4000, color = 'orange'},
        [262] = {title = 'Felony Possession of Human Remains', class = 'Felony', id = '262', months = 30, fine = 2250, color = 'orange'},
        [263] = {title = 'Accomplice to Felony Possession of Human Remains', class = 'Felony', id = '263', months = 30, fine = 2250, color = 'orange'},
        [264] = {title = 'Accessory to Felony Possession of Human', class = 'Felony', id = '264', months = 5, fine = 5, color = 'orange'},
        [265] = {title = 'Criminal Possession of a Firearm [Class 1]', class = 'Misdemeanor', id = '265', months = 7, fine = 525, color = 'orange'},
        [266] = {title = 'Criminal Possession of a Firearm [Class 2]', class = 'Felony', id = '266', months = 28, fine = 2100, color = 'orange'},
        [267] = {title = 'Criminal Possession of a Government-Issue Firearm', class = 'Felony', id = '267', months = 210, fine = 22500, color = 'orange'},
        [268] = {title = 'Criminal Possession of a Firearm [Class 3]', class = 'Felony', id = '268', months = 35, fine = 2625, color = 'orange'},
        [269] = {title = 'Possession of Explosives', class = 'Felony', id = '269', months = 1440, fine = 1440, color = 'orange'},
        [270] = {title = 'Criminal Sale of a Firearm [Class 1]', class = 'Felony', id = '270', months = 12, fine = 900, color = 'orange'},
        [271] = {title = 'Accomplice to Criminal Sale of a Firearm [Class 1]', class = 'Felony', id = '271', months = 12, fine = 900, color = 'orange'},
        [272] = {title = 'Accessory to Criminal Sale of a Firearm [Class 1]', class = 'Felony', id = '272', months = 10, fine = 720, color = 'orange'},
        [273] = {title = 'Criminal Sale of an illegal weapon', class = 'Felony', id = '273', months = 35, fine = 2625, color = 'orange'},
        [274] = {title = 'Accomplice to Criminal Sale of an illegal weapon', class = 'Felony', id = '274', months = 35, fine = 2625, color = 'orange'},
        [275] = {title = 'Accessory to Criminal Sale of an illegal weapon', class = 'Felony', id = '275', months = 28, fine = 2100, color = 'orange'},
        [276] = {title = 'Criminal Use of a Firearm', class = 'Misdemeanor', id = '276', months = 7, fine = 525, color = 'orange'},
        [277] = {title = 'Accomplice to Criminal Use of a Firearm', class = 'Misdemeanor', id = '277', months = 7, fine = 525, color = 'orange'},
        [278] = {title = 'Accessory to Criminal Use of a Firearm', class = 'Misdemeanor', id = '278', months = 6, fine = 420, color = 'orange'},
        [279] = {title = 'Brandishing non Firearm', class = 'Misdemeanor', id = '279', months = 5, fine = 375, color = 'orange'},
        [280] = {title = 'Accomplice to Brandishing non Firearm', class = 'Misdemeanor', id = '280', months = 5, fine = 375, color = 'orange'},
        [281] = {title = 'Accessory to Brandishing non Firearm', class = 'Misdemeanor', id = '281', months = 4, fine = 300, color = 'orange'},
        [282] = {title = 'Resisting Arrest', class = 'Misdemeanor', id = '282', months = 5, fine = 375, color = 'orange'},
        [283] = {title = 'Accomplice to Resisting Arrest', class = 'Misdemeanor', id = '283', months = 5, fine = 375, color = 'orange'},
        [284] = {title = 'Accessory to Resisting Arrest', class = 'Misdemeanor', id = '284', months = 4, fine = 300, color = 'orange'},
        [285] = {title = 'Jaywalking', class = 'Infraction', id = '285', months = 0, fine = 150, color = 'orange'},
        [286] = {title = 'Terrorism', class = 'Felony', id = '286', months = 0, fine = 0, color = 'orange'},
        [287] = {title = 'Treason', class = 'Felony', id = '287', months = 0, fine = 0, color = 'orange'},
        [288] = {title = 'Accomplice to Terrorism', class = 'Felony', id = '288', months = 0, fine = 0, color = 'orange'},
        [289] = {title = 'Accessory toTerrorism', class = 'Felony', id = '289', months = 0, fine = 0, color = 'orange'},
        [290] = {title = 'Weapons Trafficking', class = 'Felony', id = '290', months = 1440, fine = 1440, color = 'orange'},
        [291] = {title = 'Accomplice to Weapons Trafficking', class = 'Felony', id = '291', months = 1440, fine = 1440, color = 'orange'},
        [292] = {title = 'Accessory to Weapons Trafficking', class = 'Felony', id = '292', months = 1440, fine = 1440, color = 'orange'},
        [293] = {title = 'Criminal Possession of a Taser', class = 'Misdemeanor', id = '293', months = 21, fine = 1575, color = 'orange'},
        [294] = {title = 'Flying into Restricted Airspace', class = 'Felony', id = '294', months = 28, fine = 2100, color = 'orange'},
        [295] = {title = 'Accomplice to Flying into Restricted Airspace', class = 'Felony', id = '295', months = 28, fine = 2100, color = 'orange'},
        [296] = {title = 'Accessory to Flying into Restricted Airspace', class = 'Felony', id = '296', months = 23, fine = 1680, color = 'orange'},
        [297] = {title = 'Piloting Without a Proper License', class = 'Felony', id = '297', months = 28, fine = 2100, color = 'orange'},
        [298] = {title = 'Accomplice to Piloting Without a Proper License', class = 'Felony', id = '298', months = 28, fine = 2100, color = 'orange'},
        [299] = {title = 'Accessory to Piloting Without a Proper License', class = 'Felony', id = '299', months = 23, fine = 1680, color = 'orange'},
        [300] = {title = 'Criminal Possession of Government-issued Taser', class = 'Felony', id = '300', months = 21, fine = 1575, color = 'orange'},
        [301] = {title = 'Criminal Possession of Government-issued Flashbang', class = 'Felony', id = '301', months = 42, fine = 4500, color = 'orange'},
        [302] = {title = 'Criminal Possession of a Government Issued Baton', class = 'Misdemeanor', id = '302', months = 7, fine = 525, color = 'orange'},
        [303] = {title = 'Possession of a Silencer / Suppressor', class = 'Felony', id = '303', months = 14, fine = 900, color = 'orange'},
        [304] = {title = 'Possession of a Molotov', class = 'Felony', id = '304', months = 35, fine = 2625, color = 'orange'},
        [305] = {title = 'Criminal Use of Explosives', class = 'Felony', id = '305', months = 35, fine = 2625, color = 'orange'},
        [306] = {title = 'Accomplice to Criminal Use of Explosives', class = 'Felony', id = '306', months = 35, fine = 2625, color = 'orange'},
        [307] = {title = 'Accessory to Criminal Use of Explosives', class = 'Felony', id = '307', months = 28, fine = 2100, color = 'orange'},
        [308] = {title = 'Criminal Possession of a Government Issued Equipment', class = 'Felony', id = '308', months = 15, fine = 1125, color = 'orange'},
        [309] = {title = 'Misdemeanor Possession of Moonshine', class = 'Misdemeanor', id = '309', months = 9, fine = 675, color = 'orange'},
        [310] = {title = 'Felony Possession of', class = 'Moonshine', id = '310', months = 25, fine = 187, color = 'orange'},
        [311] = {title = 'Driving While Intoxicated', class = 'Misdemeanor', id = '311', months = 5, fine = 375, color = 'orange'},
        [312] = {title = 'Hit and Run', class = 'Misdemeanor', id = '312', months = 7, fine = 525, color = 'orange'},
        [313] = {title = 'Accomplice to Hit and Run', class = 'Misdemeanor', id = '313', months = 7, fine = 525, color = 'orange'},
        [314] = {title = 'Accessory to Hit and Run', class = 'Misdemeanor', id = '314', months = 6, fine = 420, color = 'orange'},
        [315] = {title = 'Felony Hit and Run', class = 'Felony', id = '315', months = 14, fine = 1050, color = 'orange'},
        [316] = {title = 'Accomplice to Felony Hit and Run', class = 'Felony', id = '316', months = 14, fine = 1050, color = 'orange'},
        [317] = {title = 'Accessory to Felony Hit and Run', class = 'Felony', id = '317', months = 12, fine = 840, color = 'orange'},
        [318] = {title = 'Evading', class = 'Misdemeanor', id = '318', months = 7, fine = 525, color = 'orange'},
        [319] = {title = 'Accomplice to Evading', class = 'Misdemeanor', id = '319', months = 7, fine = 525, color = 'orange'},
        [320] = {title = 'Accessory to Evading', class = 'Misdemeanor', id = '320', months = 6, fine = 420, color = 'orange'},
        [321] = {title = 'Reckless Evading', class = 'Felony', id = '321', months = 18, fine = 1350, color = 'orange'},
        [322] = {title = 'Accomplice to Reckless Evading', class = 'Felony', id = '322', months = 18, fine = 1350, color = 'orange'},
        [323] = {title = 'Accessory to Reckless Evading', class = 'Felony', id = '323', months = 15, fine = 1080, color = 'orange'},
        [324] = {title = 'Failure to Yield to Emergency Vehicle', class = 'Infraction', id = '324', months = 0, fine = 150, color = 'orange'},
        [325] = {title = 'Failure to Obey Traffic Control Devices', class = 'Infraction', id = '325', months = 0, fine = 150, color = 'orange'},
        [326] = {title = 'Negligent Driving', class = 'Infraction', id = '326', months = 0, fine = 250, color = 'orange'},
        [327] = {title = 'Reckless Driving', class = 'Felony', id = '327', months = 12, fine = 900, color = 'orange'},
        [328] = {title = 'Third Degree Speeding', class = 'Infraction', id = '328', months = 0, fine = 250, color = 'orange'},
        [329] = {title = 'Second Degree Speeding', class = 'Infraction', id = '329', months = 0, fine = 500, color = 'orange'},
        [330] = {title = 'First Degree Speeding', class = 'Infraction', id = '330', months = 0, fine = 750, color = 'orange'},
        [331] = {title = 'Operating a Motor Vehicle on a Suspended or Revoked License', class = 'Felony', id = '331', months = 14, fine = 1050, color = 'orange'},
        [332] = {title = 'Illegal Passing', class = 'Infraction', id = '332', months = 0, fine = 250, color = 'orange'},
        [333] = {title = 'Driving on the Wrong Side of The Road', class = 'Infraction', id = '333', months = 0, fine = 250, color = 'orange'},
        [334] = {title = 'Illegal Turn', class = 'Infraction', id = '334', months = 0, fine = 250, color = 'orange'},
        [335] = {title = 'Failure to Stop', class = 'Infraction', id = '335', months = 0, fine = 250, color = 'orange'},
        [336] = {title = 'Unauthorized Parking', class = 'Infraction', id = '336', months = 0, fine = 400, color = 'orange'},
        [337] = {title = 'Riding on a Sidewalk', class = 'Infraction', id = '337', months = 0, fine = 250, color = 'orange'},
        [338] = {title = 'Operating a Motor Vehicle Without Proper Identification', class = 'Infraction', id = '338', months = 0, fine = 250, color = 'orange'},
        [339] = {title = 'Unauthorized Operation of an Off-Road Vehicle', class = 'Misdemeanor', id = '339', months = 10, fine = 750, color = 'orange'},
        [340] = {title = 'Improper Window Tint', class = 'Misdemeanor', id = '340', months = 0, fine = 250, color = 'orange'},
        [341] = {title = 'Street Racing', class = 'Felony', id = '341', months = 21, fine = 1575, color = 'orange'},
        [342] = {title = 'Accomplice to Street Racing', class = 'Felony', id = '342', months = 21, fine = 1575, color = 'orange'},
        [343] = {title = 'Accessory to Street Racing', class = 'Felony', id = '343', months = 17, fine = 1260, color = 'orange'},
        [344] = {title = 'Failure to Signal', class = 'Infraction', id = '344', months = 0, fine = 10, color = 'orange'},
        [345] = {title = 'Poaching', class = 'Felony', id = '345', months = 18, fine = 1350, color = 'orange'},
        [346] = {title = 'Accomplice to Poaching', class = 'Poaching', id = '346', months = 15, fine = 1080, color = 'orange'},
        [347] = {title = 'Hunting/Fishing Without a License', class = 'Misdemeanor', id = '347', months = 5, fine = 375, color = 'orange'},
        [348] = {title = 'Hunting in an Unregulated Area', class = 'Infraction', id = '348', months = 0, fine = 500, color = 'orange'},
        [349] = {title = 'Criminal Rampage And Nonspecific Executions', class = 'Felony', id = '349', months = 210, fine = 22500, color = 'orange'},

    }
}

Config["StaffLogs"] = {
    ["NewBulletin"] = "%s Created New Bulletin.",
    ["DeleteBulletin"] = "%s Deleted Bulletin.",
    ["NewIncident"] = "%s Created New Incident.",
    ["EditIncident"] = "%s Edited Incident.",
    ["DeleteIncident"] = "%s Deleted Incident.",
    ["NewReport"] = "%s Created New Report.",
    ["EditReport"] = "%s Edited Report.",
    ["DeleteReport"] = "%s Deleted Report.",
    ["NewBolo"] = "%s Created New Bolo.",
    ["EditBolo"] = "%s Edited Bolo.",
    ["DeleteBolo"] = "%s Deleted Bolo.",
    ["DeleteMissing"] = "%s Deleted Missing Citizen."
}