-- int residenitial inside x64c > levels > interiors > int_props

--<Item>v_bar</Item>
--<Item>v_bathroom</Item>
--<Item>v_electrical</Item>
--<Item>v_kitchen</Item>
--<Item>v_office</Item>

-- UNSORTED_ONE = {
-- 	"apa_mp_h_acc_artwalll_01",
-- 	"apa_mp_h_acc_artwalll_02",
-- 	"apa_mp_h_acc_artwalll_03",
-- 	"apa_mp_h_acc_artwallm_02",
-- 	"apa_mp_h_acc_artwallm_03",
-- 	"apa_mp_h_acc_artwallm_04",
-- 	"apa_mp_h_acc_bottle_01",
-- 	"apa_mp_h_acc_bottle_02",
-- 	"apa_mp_h_acc_bowl_ceramic_01",
-- 	"apa_mp_h_acc_box_trinket_01",
-- 	"apa_mp_h_acc_box_trinket_02",
-- 	"apa_mp_h_acc_candles_01",
-- 	"apa_mp_h_acc_candles_02",
-- 	"apa_mp_h_acc_candles_04",
-- 	"apa_mp_h_acc_candles_05",
-- 	"apa_mp_h_acc_candles_06",
-- 	"apa_mp_h_acc_coffeemachine_01",
-- 	"apa_mp_h_acc_dec_head_01",
-- 	"apa_mp_h_acc_dec_plate_01",
-- 	"apa_mp_h_acc_dec_plate_02",
-- 	"apa_mp_h_acc_dec_sculpt_01",
-- 	"apa_mp_h_acc_dec_sculpt_02",
-- 	"apa_mp_h_acc_dec_sculpt_03",
-- 	"apa_mp_h_acc_drink_tray_02",
-- 	"apa_mp_h_acc_fruitbowl_01",
-- 	"apa_mp_h_acc_fruitbowl_02",
-- 	"apa_mp_h_acc_jar_02",
-- 	"apa_mp_h_acc_jar_03",
-- 	"apa_mp_h_acc_jar_04",
-- 	"apa_mp_h_acc_phone_01",
-- 	"apa_mp_h_acc_plant_palm_01",
-- 	"apa_mp_h_acc_plant_tall_01",
-- 	"apa_mp_h_acc_pot_pouri_01",
-- 	"apa_mp_h_acc_rugwooll_03",
-- 	"apa_mp_h_acc_rugwooll_04",
-- 	"apa_mp_h_acc_rugwoolm_01",
-- 	"apa_mp_h_acc_rugwoolm_02",
-- 	"apa_mp_h_acc_rugwoolm_03",
-- 	"apa_mp_h_acc_rugwoolm_04",
-- 	"apa_mp_h_acc_rugwools_01",
-- 	"apa_mp_h_acc_rugwools_03",
-- 	"apa_mp_h_acc_scent_sticks_01",
-- 	"apa_mp_h_acc_tray_01",
-- 	"apa_mp_h_acc_vase_01",
-- 	"apa_mp_h_acc_vase_02",
-- 	"apa_mp_h_acc_vase_04",
-- 	"apa_mp_h_acc_vase_05",
-- 	"apa_mp_h_acc_vase_06",
-- 	"apa_mp_h_acc_vase_flowers_01",
-- 	"apa_mp_h_acc_vase_flowers_02",
-- 	"apa_mp_h_acc_vase_flowers_03",
-- 	"apa_mp_h_acc_vase_flowers_04",
-- 	"apa_mp_h_bathtub_01",
-- 	"apa_mp_h_bed_chestdrawer_02",
-- 	"apa_mp_h_bed_double_08",
-- 	"apa_mp_h_bed_double_09",
-- 	"apa_mp_h_bed_wide_05",
-- 	"apa_mp_h_bed_with_table_02",
-- 	"apa_mp_h_din_chair_04",
-- 	"apa_mp_h_din_chair_08",
-- 	"apa_mp_h_din_chair_09",
-- 	"apa_mp_h_din_chair_12",
-- 	"apa_mp_h_din_stool_04",
-- 	"apa_mp_h_din_table_01",
-- 	"apa_mp_h_din_table_04",
-- 	"apa_mp_h_din_table_05",
-- 	"apa_mp_h_din_table_06",
-- 	"apa_mp_h_din_table_11",
-- 	"apa_mp_h_floor_lamp_int_08",
-- 	"apa_mp_h_floorlamp_a",
-- 	"apa_mp_h_floorlamp_b",
-- 	"apa_mp_h_floorlamp_c",
-- 	"apa_mp_h_lit_floorlamp_01",
-- 	"apa_mp_h_lit_floorlamp_05",
-- 	"apa_mp_h_lit_floorlamp_06",
-- 	"apa_mp_h_lit_floorlamp_17",
-- 	"apa_mp_h_lit_floorlampnight_05",
-- 	"apa_mp_h_lit_floorlampnight_14",
-- 	"apa_mp_h_lit_lamptable_005",
-- 	"apa_mp_h_lit_lamptable_02",
-- 	"apa_mp_h_lit_lamptable_04",
-- 	"apa_mp_h_lit_lamptable_09",
-- 	"apa_mp_h_lit_lamptable_14",
-- 	"apa_mp_h_lit_lamptable_17",
-- 	"apa_mp_h_lit_lamptable_21",
-- 	"apa_mp_h_lit_lamptablenight_16",
-- 	"apa_mp_h_lit_lamptablenight_24",
-- 	"apa_mp_h_lit_lightpendant_01",
-- 	"apa_mp_h_lit_lightpendant_05",
-- 	"apa_mp_h_lit_lightpendant_05b",
-- 	"apa_mp_h_stn_chairarm_01",
-- 	"apa_mp_h_stn_chairarm_02",
-- 	"apa_mp_h_stn_chairarm_03",
-- 	"apa_mp_h_stn_chairarm_09",
-- 	"apa_mp_h_stn_chairarm_11",
-- 	"apa_mp_h_stn_chairarm_12",
-- 	"apa_mp_h_stn_chairarm_13",
-- 	"apa_mp_h_stn_chairarm_23",
-- 	"apa_mp_h_stn_chairarm_24",
-- 	"apa_mp_h_stn_chairarm_25",
-- 	"apa_mp_h_stn_chairarm_26",
-- 	"apa_mp_h_stn_chairstool_12",
-- 	"apa_mp_h_stn_chairstrip_01",
-- 	"apa_mp_h_stn_chairstrip_02",
-- 	"apa_mp_h_stn_chairstrip_03",
-- 	"apa_mp_h_stn_chairstrip_04",
-- 	"apa_mp_h_stn_chairstrip_05",
-- 	"apa_mp_h_stn_chairstrip_06",
-- 	"apa_mp_h_stn_chairstrip_07",
-- 	"apa_mp_h_stn_chairstrip_08",
-- 	"apa_mp_h_stn_foot_stool_01",
-- 	"apa_mp_h_stn_foot_stool_02",
-- 	"apa_mp_h_stn_sofa2seat_02",
-- 	"apa_mp_h_stn_sofa_daybed_01",
-- 	"apa_mp_h_stn_sofa_daybed_02",
-- 	"apa_mp_h_stn_sofacorn_01",
-- 	"apa_mp_h_stn_sofacorn_05",
-- 	"apa_mp_h_stn_sofacorn_06",
-- 	"apa_mp_h_stn_sofacorn_07",
-- 	"apa_mp_h_stn_sofacorn_08",
-- 	"apa_mp_h_stn_sofacorn_09",
-- 	"apa_mp_h_stn_sofacorn_10",
-- 	"apa_mp_h_str_avunitl_01_b",
-- 	"apa_mp_h_str_avunitl_04",
-- 	"apa_mp_h_str_avunitm_01",
-- 	"apa_mp_h_str_avunitm_03",
-- 	"apa_mp_h_str_avunits_01",
-- 	"apa_mp_h_str_avunits_04",
-- 	"apa_mp_h_str_shelffloorm_02",
-- 	"apa_mp_h_str_shelffreel_01",
-- 	"apa_mp_h_str_shelfwallm_01",
-- 	"apa_mp_h_str_sideboardl_06",
-- 	"apa_mp_h_str_sideboardl_09",
-- 	"apa_mp_h_str_sideboardl_11",
-- 	"apa_mp_h_str_sideboardl_13",
-- 	"apa_mp_h_str_sideboardl_14",
-- 	"apa_mp_h_str_sideboardm_02",
-- 	"apa_mp_h_str_sideboardm_03",
-- 	"apa_mp_h_str_sideboards_01",
-- 	"apa_mp_h_str_sideboards_02",
-- 	"apa_mp_h_tab_coffee_05",
-- 	"apa_mp_h_tab_coffee_07",
-- 	"apa_mp_h_tab_coffee_08",
-- 	"apa_mp_h_tab_sidelrg_01",
-- 	"apa_mp_h_tab_sidelrg_02",
-- 	"apa_mp_h_tab_sidelrg_04",
-- 	"apa_mp_h_tab_sidelrg_07",
-- 	"apa_mp_h_tab_sidesml_01",
-- 	"apa_mp_h_tab_sidesml_02",
-- 	"apa_mp_h_table_lamp_int_08",
-- 	"apa_mp_h_yacht_armchair_01",
-- 	"apa_mp_h_yacht_armchair_03",
-- 	"apa_mp_h_yacht_armchair_04",
-- 	"apa_mp_h_yacht_barstool_01",
-- 	"apa_mp_h_yacht_bed_01",
-- 	"apa_mp_h_yacht_bed_02",
-- 	"apa_mp_h_yacht_coffee_table_01",
-- 	"apa_mp_h_yacht_coffee_table_02",
-- 	"apa_mp_h_yacht_floor_lamp_01",
-- 	"apa_mp_h_yacht_side_table_01",
-- 	"apa_mp_h_yacht_side_table_02",
-- 	"apa_mp_h_yacht_sofa_01",
-- 	"apa_mp_h_yacht_sofa_02",
-- 	"apa_mp_h_yacht_stool_01",
-- 	"apa_mp_h_yacht_strip_chair_01",
-- 	"apa_mp_h_yacht_table_lamp_01",
-- 	"apa_mp_h_yacht_table_lamp_02",
-- 	"apa_mp_h_yacht_table_lamp_03",
-- 	"apa_p_apdlc_treadmill_s",
-- 	"apa_p_h_acc_artwalll_01",
-- 	"apa_p_h_acc_artwalll_02",
-- 	"apa_p_h_acc_artwalll_03",
-- 	"apa_p_h_acc_artwalll_04",
-- 	"apa_p_h_acc_artwallm_01",
-- 	"apa_p_h_acc_artwallm_03",
-- 	"apa_p_h_acc_artwallm_04",
-- 	"apa_p_h_acc_artwalls_03",
-- 	"apa_p_h_acc_artwalls_04",
-- 	"apa_prop_cs_plastic_cup_01",
-- 	"apa_prop_flag_argentina",
-- 	"apa_prop_flag_australia",
-- 	"apa_prop_flag_austria",
-- 	"apa_prop_flag_belgium",
-- 	"apa_prop_flag_brazil",
-- 	"apa_prop_flag_canada_yt",
-- 	"apa_prop_flag_china",
-- 	"apa_prop_flag_colombia",
-- 	"apa_prop_flag_croatia",
-- 	"apa_prop_flag_czechrep",
-- 	"apa_prop_flag_denmark",
-- 	"apa_prop_flag_england",
-- 	"apa_prop_flag_eu_yt",
-- 	"apa_prop_flag_finland",
-- 	"apa_prop_flag_france",
-- 	"apa_prop_flag_german_yt",
-- 	"apa_prop_flag_hungary",
-- 	"apa_prop_flag_ireland",
-- 	"apa_prop_flag_israel",
-- 	"apa_prop_flag_italy",
-- 	"apa_prop_flag_jamaica",
-- 	"apa_prop_flag_japan_yt",
-- 	"apa_prop_flag_lstein",
-- 	"apa_prop_flag_malta",
-- 	"apa_prop_flag_mexico_yt",
-- 	"apa_prop_flag_netherlands",
-- 	"apa_prop_flag_newzealand",
-- 	"apa_prop_flag_nigeria",
-- 	"apa_prop_flag_norway",
-- 	"apa_prop_flag_palestine",
-- 	"apa_prop_flag_poland",
-- 	"apa_prop_flag_portugal",
-- 	"apa_prop_flag_puertorico",
-- 	"apa_prop_flag_russia_yt",
-- 	"apa_prop_flag_scotland_yt",
-- 	"apa_prop_flag_slovakia",
-- 	"apa_prop_flag_slovenia",
-- 	"apa_prop_flag_southafrica",
-- 	"apa_prop_flag_southkorea",
-- 	"apa_prop_flag_spain",
-- 	"apa_prop_flag_sweden",
-- 	"apa_prop_flag_switzerland",
-- 	"apa_prop_flag_turkey",
-- 	"apa_prop_flag_uk_yt",
-- 	"apa_prop_flag_us_yt",
-- 	"apa_prop_flag_wales",
-- 	"ar_prop_ar_tube_4x_xxs",
-- 	"as_prop_as_speakerdock",
-- 	"ba_prop_battle_antique_box",
-- 	"ba_prop_battle_bag_01a",
-- 	"ba_prop_battle_bag_01b",
-- 	"ba_prop_battle_bar_beerfridge_01",
-- 	"ba_prop_battle_bar_fridge_01",
-- 	"ba_prop_battle_bar_fridge_02",
-- 	"ba_prop_battle_barrier_02a",
-- 	"ba_prop_battle_cctv_cam_01a",
-- 	"ba_prop_battle_cctv_cam_01b",
-- 	"ba_prop_battle_champ_01",
-- 	"ba_prop_battle_champ_closed",
-- 	"ba_prop_battle_champ_closed_02",
-- 	"ba_prop_battle_champ_closed_03",
-- 	"ba_prop_battle_champ_open",
-- 	"ba_prop_battle_champ_open_02",
-- 	"ba_prop_battle_champ_open_03",
-- 	"ba_prop_battle_chest_closed",
-- 	"ba_prop_battle_club_chair_01",
-- 	"ba_prop_battle_club_chair_02",
-- 	"ba_prop_battle_club_chair_03",
-- 	"ba_prop_battle_club_computer_01",
-- 	"ba_prop_battle_club_computer_02",
-- 	"ba_prop_battle_club_screen",
-- 	"ba_prop_battle_club_screen_02",
-- 	"ba_prop_battle_club_screen_03",
-- 	"ba_prop_battle_club_speaker_array",
-- 	"ba_prop_battle_club_speaker_dj",
-- 	"ba_prop_battle_club_speaker_large",
-- 	"ba_prop_battle_club_speaker_med",
-- 	"ba_prop_battle_club_speaker_small",
-- 	"ba_prop_battle_coke_doll_bigbox",
-- 	"ba_prop_battle_control_console",
-- 	"ba_prop_battle_control_seat",
-- 	"ba_prop_battle_decanter_01_s",
-- 	"ba_prop_battle_decanter_02_s",
-- 	"ba_prop_battle_decanter_03_s",
-- 	"ba_prop_battle_dj_deck_01a",
-- 	"ba_prop_battle_dj_kit_mixer",
-- 	"ba_prop_battle_dj_kit_speaker",
-- 	"ba_prop_battle_dj_mixer_01a",
-- 	"ba_prop_battle_dj_mixer_01b",
-- 	"ba_prop_battle_dj_mixer_01c",
-- 	"ba_prop_battle_dj_mixer_01d",
-- 	"ba_prop_battle_dj_mixer_01e",
-- 	"ba_prop_battle_fan",
-- 	"ba_prop_battle_handbag",
-- 	"ba_prop_battle_headphones_dj",
-- 	"ba_prop_battle_hinge",
-- 	"ba_prop_battle_hobby_horse",
-- 	"ba_prop_battle_ice_bucket",
-- 	"ba_prop_battle_laptop_dj",
-- 	"ba_prop_battle_ps_box_01",
-- 	"ba_prop_battle_security_pad",
-- 	"ba_prop_battle_shot_glass_01",
-- 	"ba_prop_battle_sports_helmet",
-- 	"ba_prop_battle_trophy_dancer",
-- 	"ba_prop_battle_trophy_no1",
-- 	"ba_prop_battle_whiskey_bottle_2_s",
-- 	"ba_prop_battle_whiskey_bottle_s",
-- 	"ba_prop_battle_whiskey_opaque_s",
-- 	"ba_prop_club_champset",
-- 	"ba_prop_club_dimmer",
-- 	"ba_prop_club_dressing_board_01",
-- 	"ba_prop_club_dressing_board_02",
-- 	"ba_prop_club_dressing_board_03",
-- 	"ba_prop_club_dressing_board_04",
-- 	"ba_prop_club_dressing_board_05",
-- 	"ba_prop_club_dressing_sign_01",
-- 	"ba_prop_club_dressing_sign_02",
-- 	"ba_prop_club_dressing_sign_03",
-- 	"ba_prop_club_laptop_dj",
-- 	"ba_prop_club_laptop_dj_02",
-- 	"ba_prop_club_smoke_machine",
-- 	"ba_prop_club_tonic_bottle",
-- 	"ba_prop_club_tonic_can",
-- 	"ba_prop_club_water_bottle",
-- 	"ba_prop_int_edgy_stool",
-- 	"ba_prop_int_edgy_table_01",
-- 	"ba_prop_int_edgy_table_02",
-- 	"ba_prop_int_glam_stool",
-- 	"ba_prop_int_glam_table",
-- 	"ba_prop_int_stool_low",
-- 	"ba_prop_int_trad_table",
-- 	"beerrow_local",
-- 	"beerrow_world",
-- 	"bkr_prop_biker_barstool_01",
-- 	"bkr_prop_biker_barstool_02",
-- 	"bkr_prop_biker_barstool_03",
-- 	"bkr_prop_biker_barstool_04",
-- 	"bkr_prop_biker_campbed_01",
-- 	"bkr_prop_biker_case_shut",
-- 	"bkr_prop_biker_ceiling_fan_base",
-- 	"bkr_prop_biker_chair_01",
-- 	"bkr_prop_biker_chairstrip_01",
-- 	"bkr_prop_biker_chairstrip_02",
-- 	"bkr_prop_biker_garage_locker_01",
-- 	"bkr_prop_biker_gcase_s",
-- 	"bkr_prop_biker_safebody_01a",
-- 	"bkr_prop_biker_safedoor_01a",
-- 	"bkr_prop_clubhouse_arm_wrestle_01a",
-- 	"bkr_prop_clubhouse_arm_wrestle_02a",
-- 	"bkr_prop_clubhouse_armchair_01a",
-- 	"bkr_prop_clubhouse_blackboard_01a",
-- 	"bkr_prop_clubhouse_chair_01",
-- 	"bkr_prop_clubhouse_chair_03",
-- 	"bkr_prop_clubhouse_jukebox_01a",
-- 	"bkr_prop_clubhouse_jukebox_01b",
-- 	"bkr_prop_clubhouse_jukebox_02a",
-- 	"bkr_prop_clubhouse_laptop_01a",
-- 	"bkr_prop_clubhouse_laptop_01b",
-- 	"bkr_prop_clubhouse_offchair_01a",
-- 	"bkr_prop_clubhouse_sofa_01a",
-- 	"bkr_prop_coke_bakingsoda",
-- 	"bkr_prop_coke_bakingsoda_o",
-- 	"bkr_prop_coke_press_01b",
-- 	"bkr_prop_coke_press_01b_frag_",
-- 	"bkr_prop_coke_scale_03",
-- 	"bkr_prop_coke_striplamp_short_01a",
-- 	"bkr_prop_fakeid_clipboard_01a",
-- 	"bkr_prop_fakeid_deskfan_01a",
-- 	"bkr_prop_fakeid_foiltipper",
-- 	"bkr_prop_fakeid_laminator",
-- 	"bkr_prop_fakeid_penclipboard",
-- 	"bkr_prop_fakeid_table",
-- 	"bkr_prop_fakeid_tablet_01a",
-- 	"ch_prop_arcade_penetrator_01a",
-- 	"ch_prop_arcade_street_01b",
-- 	"ch_prop_arcade_street_01c",
-- 	"ch_prop_arcade_street_01d",
-- 	"ch_prop_arcade_wizard_01a",
-- 	"ch_prop_casino_track_chair_01",
-- 	"ch_prop_ch_bag_01a",
-- 	"ch_prop_ch_bag_02a",
-- 	"ch_prop_ch_camera_01",
-- 	"ch_prop_ch_cartridge_01a",
-- 	"ch_prop_ch_cartridge_01b",
-- 	"ch_prop_ch_cartridge_01c",
-- 	"ch_prop_ch_case_01a",
-- 	"ch_prop_ch_cctv_cam_01a",
-- 	"ch_prop_ch_cctv_cam_02a",
-- 	"ch_prop_ch_cctv_wall_atta_01a",
-- 	"ch_prop_ch_coffe_table_02",
-- 	"ch_prop_ch_hatch_liftshaft_01a",
-- 	"ch_prop_ch_heist_drill",
-- 	"ch_prop_ch_lamp_01",
-- 	"ch_prop_ch_lamp_ceiling_01a",
-- 	"ch_prop_ch_lamp_ceiling_02a",
-- 	"ch_prop_ch_lamp_ceiling_02b",
-- 	"ch_prop_ch_lamp_ceiling_03a",
-- 	"ch_prop_ch_lamp_ceiling_04a",
-- 	"ch_prop_ch_lamp_ceiling_g_01a",
-- 	"ch_prop_ch_lamp_ceiling_g_01b",
-- 	"ch_prop_ch_lamp_ceiling_w_01a",
-- 	"ch_prop_ch_lamp_ceiling_w_01b",
-- 	"ch_prop_ch_lamp_wall_01a",
-- 	"ch_prop_ch_laundry_machine_01a",
-- 	"ch_prop_ch_laundry_shelving_01a",
-- 	"ch_prop_ch_laundry_shelving_01b",
-- 	"ch_prop_ch_laundry_shelving_01c",
-- 	"ch_prop_ch_laundry_shelving_02a",
-- 	"ch_prop_ch_service_locker_01c",
-- 	"ch_prop_ch_service_locker_02a",
-- 	"ch_prop_ch_service_locker_02b",
-- 	"ch_prop_ch_service_trolley_01a",
-- 	"ch_prop_ch_trophy_brawler_01a",
-- 	"ch_prop_ch_trophy_cabs_01a",
-- 	"ch_prop_ch_trophy_claw_01a",
-- 	"ch_prop_ch_trophy_gunner_01a",
-- 	"ch_prop_ch_trophy_king_01a",
-- 	"ch_prop_ch_trophy_love_01a",
-- 	"ch_prop_ch_trophy_monkey_01a",
-- 	"ch_prop_ch_trophy_patriot_01a",
-- 	"ch_prop_ch_trophy_racer_01a",
-- 	"ch_prop_ch_trophy_retro_01a",
-- 	"ch_prop_ch_trophy_strife_01a",
-- 	"ch_prop_ch_trophy_teller_01a",
-- 	"ch_prop_ch_utility_light_wall_01a",
-- 	"ch_prop_ch_vase_01a",
-- 	"ch_prop_ch_vase_02a",
-- 	"ch_prop_ch_wallart_01a",
-- 	"ch_prop_ch_wallart_02a",
-- 	"ch_prop_ch_wallart_03a",
-- 	"ch_prop_ch_wallart_04a",
-- 	"ch_prop_ch_wallart_05a",
-- 	"ch_prop_ch_wallart_06a",
-- 	"ch_prop_ch_wallart_07a",
-- 	"ch_prop_ch_wallart_08a",
-- 	"ch_prop_ch_wallart_09a",
-- 	"ch_prop_champagne_01a",
-- 	"ch_prop_vault_painting_01c",
-- 	"ch_prop_vault_painting_01d",
-- 	"ch_prop_vault_painting_01e",
-- 	"ch_prop_vault_painting_01f",
-- 	"ch_prop_vault_painting_01g",
-- 	"ch_prop_vault_painting_01h",
-- 	"ch_prop_vault_painting_01i",
-- 	"ch_prop_vault_painting_01j",
-- 	"ch_prop_whiteboard",
-- 	"ch_prop_whiteboard_02",
-- 	"ch_prop_whiteboard_03",
-- 	"ch_prop_whiteboard_04",
-- },

-- UNSORTED_TWO = {
-- 	"ex_mp_h_acc_artwalll_02",
-- 	"ex_mp_h_acc_artwalll_03",
-- 	"ex_mp_h_acc_artwallm_02",
-- 	"ex_mp_h_acc_artwallm_03",
-- 	"ex_mp_h_acc_artwallm_04",
-- 	"ex_mp_h_acc_bottle_01",
-- 	"ex_mp_h_acc_bowl_ceramic_01",
-- 	"ex_mp_h_acc_box_trinket_01",
-- 	"ex_mp_h_acc_box_trinket_02",
-- 	"ex_mp_h_acc_candles_01",
-- 	"ex_mp_h_acc_candles_02",
-- 	"ex_mp_h_acc_candles_04",
-- 	"ex_mp_h_acc_candles_05",
-- 	"ex_mp_h_acc_candles_06",
-- 	"ex_mp_h_acc_coffeemachine_01",
-- 	"ex_mp_h_acc_dec_head_01",
-- 	"ex_mp_h_acc_dec_plate_01",
-- 	"ex_mp_h_acc_dec_plate_02",
-- 	"ex_mp_h_acc_dec_sculpt_01",
-- 	"ex_mp_h_acc_dec_sculpt_02",
-- 	"ex_mp_h_acc_dec_sculpt_03",
-- 	"ex_mp_h_acc_fruitbowl_01",
-- 	"ex_mp_h_acc_fruitbowl_02",
-- 	"ex_mp_h_acc_plant_palm_01",
-- 	"ex_mp_h_acc_plant_tall_01",
-- 	"ex_mp_h_acc_rugwoolm_04",
-- 	"ex_mp_h_acc_scent_sticks_01",
-- 	"ex_mp_h_acc_tray_01",
-- 	"ex_mp_h_acc_vase_01",
-- 	"ex_mp_h_acc_vase_02",
-- 	"ex_mp_h_acc_vase_04",
-- 	"ex_mp_h_acc_vase_05",
-- 	"ex_mp_h_acc_vase_06",
-- 	"ex_mp_h_acc_vase_flowers_01",
-- 	"ex_mp_h_acc_vase_flowers_02",
-- 	"ex_mp_h_acc_vase_flowers_03",
-- 	"ex_mp_h_acc_vase_flowers_04",
-- 	"ex_mp_h_din_chair_04",
-- 	"ex_mp_h_din_chair_08",
-- 	"ex_mp_h_din_chair_09",
-- 	"ex_mp_h_din_chair_12",
-- 	"ex_mp_h_din_stool_04",
-- 	"ex_mp_h_din_table_01",
-- 	"ex_mp_h_din_table_04",
-- 	"ex_mp_h_din_table_05",
-- 	"ex_mp_h_din_table_06",
-- 	"ex_mp_h_din_table_11",
-- 	"ex_mp_h_lit_lamptable_02",
-- 	"ex_mp_h_lit_lightpendant_01",
-- 	"ex_mp_h_off_chairstrip_01",
-- 	"ex_mp_h_off_easychair_01",
-- 	"ex_mp_h_off_sofa_003",
-- 	"ex_mp_h_off_sofa_01",
-- 	"ex_mp_h_off_sofa_02",
-- 	"ex_mp_h_stn_chairarm_03",
-- 	"ex_mp_h_stn_chairarm_24",
-- 	"ex_mp_h_stn_chairstrip_01",
-- 	"ex_mp_h_stn_chairstrip_010",
-- 	"ex_mp_h_stn_chairstrip_011",
-- 	"ex_mp_h_stn_chairstrip_05",
-- 	"ex_mp_h_stn_chairstrip_07",
-- 	"ex_mp_h_tab_coffee_05",
-- 	"ex_mp_h_tab_coffee_08",
-- 	"ex_mp_h_tab_sidelrg_07",
-- 	"ex_mp_h_yacht_barstool_01",
-- 	"ex_mp_h_yacht_coffee_table_01",
-- 	"ex_mp_h_yacht_coffee_table_02",
-- 	"ex_office_citymodel_01",
-- 	"ex_office_swag_furcoats",
-- 	"ex_office_swag_furcoats2",
-- 	"ex_office_swag_furcoats3",
-- 	"ex_p_ex_decanter_01_s",
-- 	"ex_p_ex_decanter_02_s",
-- 	"ex_p_ex_decanter_03_s",
-- 	"ex_p_ex_tumbler_01_empty",
-- 	"ex_p_ex_tumbler_01_s",
-- 	"ex_p_ex_tumbler_02_empty",
-- 	"ex_p_ex_tumbler_02_s",
-- 	"ex_p_ex_tumbler_03_empty",
-- 	"ex_p_ex_tumbler_03_s",
-- 	"ex_p_ex_tumbler_04_empty",
-- 	"ex_p_h_acc_artwalll_01",
-- 	"ex_p_h_acc_artwalll_03",
-- 	"ex_p_h_acc_artwallm_01",
-- 	"ex_p_h_acc_artwallm_03",
-- 	"ex_p_h_acc_artwallm_04",
-- 	"ex_prop_adv_case_sm_02",
-- 	"ex_prop_ashtray_luxe_02",
-- 	"ex_prop_ex_console_table_01",
-- 	"ex_prop_ex_laptop_01a",
-- 	"ex_prop_ex_toolchest_01",
-- 	"ex_prop_ex_tv_flat_01",
-- 	"ex_prop_exec_ashtray_01",
-- 	"ex_prop_exec_award_bronze",
-- 	"ex_prop_exec_award_diamond",
-- 	"ex_prop_exec_award_gold",
-- 	"ex_prop_exec_award_plastic",
-- 	"ex_prop_exec_award_silver",
-- 	"ex_prop_exec_bed_01",
-- 	"ex_prop_monitor_01_ex",
-- 	"ex_prop_offchair_exec_01",
-- 	"ex_prop_offchair_exec_02",
-- 	"ex_prop_offchair_exec_03",
-- 	"ex_prop_offchair_exec_04",
-- 	"ex_prop_tv_settop_box",
-- 	"ex_prop_tv_settop_remote",
-- 	"gr_dlc_gr_yacht_props_glass_01",
-- 	"gr_dlc_gr_yacht_props_glass_02",
-- 	"gr_dlc_gr_yacht_props_glass_03",
-- 	"gr_dlc_gr_yacht_props_glass_04",
-- 	"gr_dlc_gr_yacht_props_glass_05",
-- 	"gr_dlc_gr_yacht_props_glass_06",
-- 	"gr_dlc_gr_yacht_props_glass_07",
-- 	"gr_dlc_gr_yacht_props_glass_08",
-- 	"gr_dlc_gr_yacht_props_glass_09",
-- 	"gr_dlc_gr_yacht_props_glass_10",
-- 	"gr_dlc_gr_yacht_props_lounger",
-- 	"gr_dlc_gr_yacht_props_seat_01",
-- 	"gr_dlc_gr_yacht_props_seat_02",
-- 	"gr_dlc_gr_yacht_props_seat_03",
-- 	"gr_dlc_gr_yacht_props_table_01",
-- 	"gr_dlc_gr_yacht_props_table_02",
-- 	"gr_dlc_gr_yacht_props_table_03",
-- 	"gr_prop_bunker_bed_01",
-- 	"gr_prop_bunker_deskfan_01a",
-- 	"gr_prop_gr_campbed_01",
-- 	"gr_prop_gr_carcreeper",
-- 	"gr_prop_gr_chair02_ped",
-- 	"gr_prop_gr_cnc_01b",
-- 	"gr_prop_gr_cnc_01c",
-- 	"gr_prop_gr_console_01",
-- 	"gr_prop_gr_drill_01a",
-- 	"gr_prop_gr_driver_01a",
-- 	"gr_prop_gr_fnclink_03e",
-- 	"gr_prop_gr_fnclink_03f",
-- 	"gr_prop_gr_fnclink_03g",
-- 	"gr_prop_gr_fnclink_03gate3",
-- 	"gr_prop_gr_fnclink_03h",
-- 	"gr_prop_gr_fnclink_03i",
-- 	"gr_prop_gr_grinder_01a",
-- 	"gr_prop_gr_hammer_01",
-- 	"gr_prop_gr_hobo_stove_01",
-- 	"gr_prop_gr_laptop_01a",
-- 	"gr_prop_gr_laptop_01b",
-- 	"gr_prop_gr_laptop_01c",
-- 	"gr_prop_gr_lathe_01a",
-- 	"gr_prop_gr_lathe_01b",
-- 	"gr_prop_gr_lathe_01c",
-- 	"gr_prop_gr_offchair_01a",
-- 	"gr_prop_gr_vertmill_01a",
-- 	"gr_prop_gr_vertmill_01b",
-- 	"gr_prop_gr_vertmill_01c",
-- 	"gr_prop_gr_vice_01a",
-- 	"hei_heist_acc_artgolddisc_01",
-- 	"hei_heist_acc_artgolddisc_02",
-- 	"hei_heist_acc_artgolddisc_03",
-- 	"hei_heist_acc_artgolddisc_04",
-- 	"hei_heist_acc_artwalll_01",
-- 	"hei_heist_acc_artwallm_01",
-- 	"hei_heist_acc_box_trinket_01",
-- 	"hei_heist_acc_box_trinket_02",
-- 	"hei_heist_acc_candles_01",
-- 	"hei_heist_acc_flowers_01",
-- 	"hei_heist_acc_flowers_02",
-- 	"hei_heist_acc_plant_tall_01",
-- 	"hei_heist_acc_rughidel_01",
-- 	"hei_heist_acc_rugwooll_01",
-- 	"hei_heist_acc_rugwooll_02",
-- 	"hei_heist_acc_rugwooll_03",
-- 	"hei_heist_acc_sculpture_01",
-- 	"hei_heist_acc_storebox_01",
-- 	"hei_heist_acc_tray_01",
-- 	"hei_heist_acc_vase_01",
-- 	"hei_heist_acc_vase_02",
-- 	"hei_heist_acc_vase_03",
-- 	"hei_heist_bed_chestdrawer_04",
-- 	"hei_heist_bed_double_08",
-- 	"hei_heist_bed_table_dble_04",
-- 	"hei_heist_cs_beer_box",
-- 	"hei_heist_din_chair_01",
-- 	"hei_heist_din_chair_02",
-- 	"hei_heist_din_chair_03",
-- 	"hei_heist_din_chair_04",
-- 	"hei_heist_din_chair_05",
-- 	"hei_heist_din_chair_06",
-- 	"hei_heist_din_chair_08",
-- 	"hei_heist_din_chair_09",
-- 	"hei_heist_din_table_01",
-- 	"hei_heist_din_table_04",
-- 	"hei_heist_din_table_06",
-- 	"hei_heist_din_table_07",
-- 	"hei_heist_kit_coffeemachine_01",
-- 	"hei_heist_lit_floorlamp_01",
-- 	"hei_heist_lit_floorlamp_02",
-- 	"hei_heist_lit_floorlamp_03",
-- 	"hei_heist_lit_floorlamp_04",
-- 	"hei_heist_lit_floorlamp_05",
-- 	"hei_heist_lit_lamptable_02",
-- 	"hei_heist_lit_lamptable_03",
-- 	"hei_heist_lit_lamptable_04",
-- 	"hei_heist_lit_lamptable_06",
-- 	"hei_heist_lit_lightpendant_003",
-- 	"hei_heist_lit_lightpendant_01",
-- 	"hei_heist_lit_lightpendant_02",
-- 	"hei_heist_sh_bong_01",
-- 	"hei_heist_stn_benchshort",
-- 	"hei_heist_stn_chairarm_01",
-- 	"hei_heist_stn_chairarm_03",
-- 	"hei_heist_stn_chairarm_04",
-- 	"hei_heist_stn_chairarm_06",
-- 	"hei_heist_stn_chairstrip_01",
-- 	"hei_heist_stn_sofa2seat_02",
-- 	"hei_heist_stn_sofa2seat_03",
-- 	"hei_heist_stn_sofa2seat_06",
-- 	"hei_heist_stn_sofa3seat_01",
-- 	"hei_heist_stn_sofa3seat_02",
-- 	"hei_heist_stn_sofa3seat_06",
-- 	"hei_heist_stn_sofacorn_05",
-- 	"hei_heist_stn_sofacorn_06",
-- 	"hei_heist_str_avunitl_01",
-- 	"hei_heist_str_avunitl_03",
-- 	"hei_heist_str_avunits_01",
-- 	"hei_heist_str_sideboardl_02",
-- 	"hei_heist_str_sideboardl_03",
-- 	"hei_heist_str_sideboardl_04",
-- 	"hei_heist_str_sideboardl_05",
-- 	"hei_heist_str_sideboards_02",
-- 	"hei_heist_tab_coffee_05",
-- 	"hei_heist_tab_coffee_06",
-- 	"hei_heist_tab_coffee_07",
-- 	"hei_heist_tab_sidelrg_01",
-- 	"hei_heist_tab_sidelrg_02",
-- 	"hei_heist_tab_sidelrg_04",
-- 	"hei_heist_tab_sidesml_01",
-- 	"hei_heist_tab_sidesml_02",
-- 	"hei_id2_lod_emissive_ref",

-- },

-- WALLS_AND_FLOORS = {
-- 	"drywall_natural",
-- 	"dwallblue_2mk2",
-- 	"dwallblue_mk2",
-- 	"dwallblue_ww",
-- 	"firstbrick_1x",
-- 	"fobrick_1x",
-- 	"freshintbricks_i1x",
-- 	"future_hexwall",
-- 	"girl_i1x",
-- 	"gold_i1x",
-- 	"grass_1x",
-- 	"gravroad_1x",
-- 	"gray_wallblend",
-- 	"gray_walltexture",
-- 	"green_wallblend",
-- 	"green_walltexture",
-- 	"groundpathmix_1x",
-- 	"hardwooda_1x",
-- 	"hardwoodtile_1x",
-- 	"horrorbrick_e1x",
-- 	"lavender_i1x",
-- 	"lightgray_walltexture",
-- 	"lime_walltexture",
-- 	"limetile_1x",
-- 	"lushscrub_1x",
-- 	"lushsoil_1x",
-- 	"marbrickwall_1x",
-- 	"marbrickwall_2x",
-- 	"mbn_glosswoodwall_2mk2",
-- 	"mbn_glosswoodwall_mk2",
-- 	"mbn_glosswoodwall_ww",
-- 	"melon_i1x",
-- 	"mossone_1x",
-- 	"mud_i1x",
-- 	"mycarp_1x",
-- 	"mycarp2_1x",
-- 	"mywall_1x",
-- 	"mywall_2x",
-- 	"mywallb_1x",
-- 	"mywallb_2x",
-- 	"mywallg_1x",
-- 	"mywallg_2x",
-- 	"mywallgr_1x",
-- 	"mywallgr_2x",
-- 	"mywallpb_1x",
-- 	"mywallpb_2x",
-- 	"mywallr_1x",
-- 	"mywallr_2x",
-- 	"mywally_1x",
-- 	"mywally_2x",
-- 	"ncarpb_i1x",
-- 	"ncarpc_i1x",
-- 	"ncarpg_i1x",
-- 	"ncarph_i1x",
-- 	"neon_i1x",
-- 	"nwoodcherry_i1x",
-- 	"officecarp_i1x",
-- 	"old_drywall",
-- 	"orange_i1x",
-- 	"orange_walltexture",
-- 	"orangetile_1x",
-- 	"outdoorwood_1x",
-- 	"panelwoodin_1x",
-- 	"panelwoodout_1x",
-- 	"peach_walltexture",
-- 	"pink_walltexture",
-- 	"pinktile_1x",
-- 	"plain_walltexture",
-- 	"plasterboard_i1x",
-- 	"plasterwall_1x",
-- 	"plasterwall_2x",
-- 	"plastileceiling_i1x",
-- 	"plum_walltexture",
-- 	"pooltile_1x",
-- 	"privacyglass_1x",
-- 	"purpfluid_i1x",
-- 	"purple_walltexture",
-- 	"purptile_1x",
-- 	"rainbowtile_1x",
-- 	"red_i1x",
-- 	"red_wallblend",
-- 	"red_walltexture",
-- 	"redstonecrumb_1x",
-- 	"roof2_1x",
-- 	"roofone_1x",
-- 	"rustfloortile_1x",
-- 	"rustmetal_1x",
-- 	"s1_brickwallpaper1_2mk2",
-- 	"s1_brickwallpaper1_mb2",
-- 	"s1_brickwallpaper1_mb4",
-- 	"s1_brickwallpaper1_mk2",
-- 	"sand_1x",
-- 	"schoolwall_new",
-- 	"sea_i1x",
-- 	"sewerconcrete_1x",
-- 	"sharpstone_1x",
-- 	"slumconcrete_1x",
-- 	"snow_i1x",
-- 	"teal_walltexture",
-- 	"thinwall_brick",
-- 	"thinwall_brick2",
-- 	"thinwall_brickblue",
-- 	"thinwall_brickred",
-- 	"thinwall_brickschool",
-- 	"thinwall_brickwhite",
-- 	"thinwall_flower_blue",
-- 	"thinwall_flower_red",
-- 	"thinwall_flower_yellow",
-- 	"wall_future_hex",
-- 	"wall_thick_red",
-- 	"wall_thick_white",
-- 	"wall_thick_yellow",
-- 	"wall_white_b",
-- 	"wallishplain_1x",
-- 	"wallishplain_2x",
-- 	"wallishred_1x",
-- 	"wallishred_2x",
-- 	"wallroom_1x",
-- 	"wallroom_2x",
-- 	"white_walltexture",
-- 	"wind1_1x",
-- 	"woodowall_1x",
-- 	"woodowall_2x",
-- 	"woodowall2_1x",
-- 	"woodowall2_2x",
-- 	"yellow_walltexture",
-- 	"yellowleaf_1x",
-- 	"yelltile_1x",
-- 	"airconceil_i1x",
-- 	"alleywall_1x",
-- 	"alleywall_2x",
-- 	"awallblue_2mk2",
-- 	"awallblue_mk2",
-- 	"awallblue_ww",
-- 	"awallgreen_2mk2",
-- 	"awallgreen_mk2",
-- 	"awallorange_2mk2",
-- 	"awallorange_mk2",
-- 	"awallorange_ww",
-- 	"awallpink_2mk2",
-- 	"awallpink_mk2",
-- 	"awallpink_ww",
-- 	"awallred_2mk2",
-- 	"awallred_mk2",
-- 	"baby_i1x",
-- 	"beachscrub_1x",
-- 	"bigblack_hex",
-- 	"black_stone_2_flat_big",
-- 	"black_stone_tiles",
-- 	"black_stone_tiles_small",
-- 	"black_tiles",
-- 	"black_wallblend",
-- 	"black_walltexture",
-- 	"blue_wallblend",
-- 	"blue_walltexture",
-- 	"bluefuzzcarp_1x",
-- 	"bluetile_1x",
-- 	"bluetilewall_1x",
-- 	"bluetilewall_2x",
-- 	"bluewoodwall_1x",
-- 	"bluewoodwall_2x",
-- 	"boy_i1x",
-- 	"brick_plain_wall",
-- 	"brick_wallpatch",
-- 	"brick_wallschool",
-- 	"brick_walltexture2",
-- 	"brickhidef_1x",
-- 	"brightgreen_i1x",
-- 	"brokenplaster_i1x",
-- 	"brown_walltexture",
-- 	"browntextcarp_1x",
-- 	"bwallog_2mk2",
-- 	"bwallog_mk2",
-- 	"bwallog_ww",
-- 	"bwallred_2mk2",
-- 	"bwallred_mk2",
-- 	"bwallred_ww",
-- 	"canyon_1x",
-- 	"ceilingpaintdip_1x",
-- 	"cementwall_1x",
-- 	"cementwall_2x",
-- 	"cheebafloor_1x",
-- 	"cherry_walltexture",
-- 	"coal_i1x",
-- 	"crackedsidewalk_1x",
-- 	"cwallblue_2mk2",
-- 	"cwallblue_mk2",
-- 	"darkbrown_walltexture",
-- 	"darktile_1x",
-- 	"dirt_1x",
-- 	"dirtydarktile_1x"
-- },


-- UNSORTED_THREE = {
-- 	"hei_prop_bank_cctv_01",
-- 	"hei_prop_bank_cctv_02",
-- 	"hei_prop_bank_ornatelamp",
-- 	"hei_prop_hei_warehousetrolly",
-- 	"hei_prop_hei_warehousetrolly_02",
-- 	"hei_prop_heist_box",
-- 	"imp_prop_air_compressor_01a",
-- 	"imp_prop_axel_stand_01a",
-- 	"imp_prop_bench_grinder_01a",
-- 	"imp_prop_bench_vice_01a",
-- 	"imp_prop_car_jack_01a",
-- 	"imp_prop_drill_01a",
-- 	"imp_prop_grinder_01a",
-- 	"imp_prop_impact_driver_01a",
-- 	"imp_prop_tool_box_01a",
-- 	"imp_prop_tool_box_01b",
-- 	"imp_prop_tool_box_02a",
-- 	"imp_prop_tool_box_02b",
-- 	"imp_prop_tool_cabinet_01a",
-- 	"imp_prop_tool_cabinet_01b",
-- 	"imp_prop_tool_cabinet_01c",
-- 	"imp_prop_tool_chest_01a",
-- 	"imp_prop_tool_draw_01a",
-- 	"imp_prop_tool_draw_01b",
-- 	"imp_prop_tool_draw_01c",
-- 	"imp_prop_tool_draw_01d",
-- 	"imp_prop_tool_draw_01e",
-- 	"imp_prop_welder_01a",
-- 	"imp_prop_wheel_balancer_01a",
-- 	"ng_proc_food_aple1a",
-- 	"ng_proc_food_aple2a",
-- 	"ng_proc_food_bag01a",
-- 	"ng_proc_food_bag02a",
-- 	"ng_proc_food_burg01a",
-- 	"ng_proc_food_burg02a",
-- 	"ng_proc_food_burg02c",
-- 	"ng_proc_food_chips01a",
-- 	"ng_proc_food_chips01b",
-- 	"ng_proc_food_chips01c",
-- 	"ng_proc_food_nana1a",
-- 	"ng_proc_food_nana2a",
-- 	"ng_proc_food_ornge1a",
-- 	"ng_proc_inhaler01a",
-- 	"ng_proc_ojbot_01a",
-- 	"ng_proc_paintcan01a",
-- 	"ng_proc_paintcan02a",
-- 	"ng_proc_pizza01a",
-- 	"p_armchair_01_s",
-- 	"p_attache_case_01_s",
-- 	"p_balaclavamichael_s",
-- 	"p_binbag_01_s",
-- 	"p_counter_04_glass",
-- 	"p_cs_beachtowel_01_s",
-- 	"p_cs_bottle_01",
-- 	"p_cs_bowl_01b_s",
-- 	"p_cs_clipboard",
-- 	"p_cs_clothes_box_s",
-- 	"p_cs_laptop_02",
-- 	"p_cs_laptop_02_w",
-- 	"p_cs_locker_01",
-- 	"p_cs_locker_01_s",
-- 	"p_cs_locker_02",
-- 	"p_cs_locker_door_01",
-- 	"p_cs_locker_door_01b",
-- 	"p_cs_locker_door_02",
-- 	"p_cs_shot_glass_s",
-- 	"p_cs_toaster_s",
-- 	"p_defilied_ragdoll_01_s",
-- 	"p_devin_box_01_s",
-- 	"p_dinechair_01_s",
-- 	"p_folding_chair_01_s",
-- 	"p_gaffer_tape_s",
-- 	"p_gasmask_s",
-- 	"p_idol_case_s",
-- 	"p_ilev_p_easychair_s",
-- 	"p_ing_coffeecup_01",
-- 	"p_ing_coffeecup_02",
-- 	"p_ing_microphonel_01",
-- 	"p_int_jewel_mirror",
-- 	"p_int_jewel_plant_01",
-- 	"p_int_jewel_plant_02",
-- 	"p_laptop_02_s",
-- 	"p_ld_am_ball_01",
-- 	"p_lev_sofa_s",
-- 	"p_orleans_mask_s",
-- 	"p_ortega_necklace_s",
-- 	"p_oscar_necklace_s",
-- 	"p_overalls_02_s",
-- 	"p_pallet_02a_s",
-- 	"p_panties_s",
-- 	"p_patio_lounger1_s",
-- 	"p_pharm_unit_01",
-- 	"p_pharm_unit_02",
-- 	"p_planning_board_01",
-- 	"p_planning_board_02",
-- 	"p_planning_board_03",
-- 	"p_planning_board_04",
-- 	"p_res_sofa_l_s",
-- 	"p_soloffchair_s",
-- 	"p_tennis_bag_01_s",
-- 	"p_tourist_map_01_s",
-- 	"p_v_med_p_sofa_s",
-- 	"p_v_res_tt_bed_s",
-- 	"p_w_grass_gls_s",
-- 	"p_wade_necklace_s",
-- 	"p_whiskey_bottle_s",
-- 	"p_whiskey_notop",
-- 	"p_whiskey_notop_empty",
-- 	"p_yoga_mat_02_s",
-- 	"p_yoga_mat_03_s",
-- 	"port_xr_elecbox_1",
-- 	"port_xr_elecbox_2",
-- 	"port_xr_elecbox_3",
-- 	"port_xr_fire",
-- 	"port_xr_firehose",
-- 	"port_xr_lifep",
-- 	"port_xr_lightdoor",
-- 	"port_xr_lighthal",
-- 	"port_xr_lightspot",
-- 	"prop_air_lights_01a",
-- 	"prop_air_lights_01b",
-- 	"prop_air_lights_02a",
-- 	"prop_air_lights_02b",
-- 	"prop_air_lights_03a",
-- 	"prop_airhockey_01",
-- 	"prop_alarm_01",
-- 	"prop_alarm_02",
-- 	"prop_aloevera_01",
-- 	"prop_am_box_wood_01",
-- 	"prop_amb_40oz_02",
-- 	"prop_amb_ciggy_01",
-- 	"prop_amb_donut",
-- 	"prop_amp_01",
-- 	"prop_apple_box_01",
-- 	"prop_apple_box_02",
-- 	"prop_arc_blueprints_01",
-- 	"prop_ball_box",
-- 	"prop_bandsaw_01",
-- 	"prop_bar_beerfridge_01",
-- 	"prop_bar_ice_01",
-- 	"prop_bar_lemons",
-- 	"prop_bar_limes",
-- 	"prop_bar_measrjug",
-- 	"prop_bar_napkindisp",
-- 	"prop_bar_nuts",
-- 	"prop_bar_stool_01",

-- }



misc1 = {
	[1] = { ["object"] = "prop_bin_11b", ["price"] = 100, ["name"] = "Bin Misc" },
	[2] = { ["object"] = "prop_bin_11a", ["price"] = 100, ["name"] = "Bin Misc" },
	[3] = { ["object"] = "prop_bin_10a", ["price"] = 100, ["name"] = "Bin Misc" },
	[4] = { ["object"] = "prop_bin_07b", ["price"] = 100, ["name"] = "Bin Misc" },
	[5] = { ["object"] = "prop_bin_04a", ["price"] = 100, ["name"] = "Bin Misc" },
	[6] = { ["object"] = "prop_bin_03a", ["price"] = 100, ["name"] = "Bin Misc" },
	[7] = { ["object"] = "prop_bikini_disp_06", ["price"] = 100, ["name"] = "Bikini Misc" },
	[8] = { ["object"] = "prop_bikini_disp_05", ["price"] = 100, ["name"] = "Bikini Misc" },
	[9] = { ["object"] = "prop_bikini_disp_04", ["price"] = 100, ["name"] = "Bikini Misc" },
	[10] = { ["object"] = "prop_bikini_disp_03", ["price"] = 100, ["name"] = "Bikini Misc" },
	[11] = { ["object"] = "prop_bikini_disp_02", ["price"] = 100, ["name"] = "Bikini Misc" },
	[12] = { ["object"] = "prop_bikini_disp_01", ["price"] = 100, ["name"] = "Bikini Misc" },
	[13] = { ["object"] = "prop_beware_dog_sign", ["price"] = 100, ["name"] = "Sign Misc" },
	[14] = { ["object"] = "prop_beggers_sign_04", ["price"] = 100, ["name"] = "Sign Misc" },
	[15] = { ["object"] = "prop_beggers_sign_03", ["price"] = 100, ["name"] = "Sign Misc" },
	[16] = { ["object"] = "prop_beggers_sign_02", ["price"] = 100, ["name"] = "Sign Misc" },
	[17] = { ["object"] = "prop_beggers_sign_01", ["price"] = 100, ["name"] = "Sign Misc" },
	[18] = { ["object"] = "prop_beerdusche", ["price"] = 100, ["name"] = "Beer Misc" },
	[19] = { ["object"] = "prop_beer_stzopen", ["price"] = 100, ["name"] = "Beer Misc" },
	[20] = { ["object"] = "prop_beer_stz", ["price"] = 100, ["name"] = "Beer Misc" },
	[21] = { ["object"] = "prop_beer_pride", ["price"] = 100, ["name"] = "Beer Misc" },
	[22] = { ["object"] = "prop_beer_pissh", ["price"] = 100, ["name"] = "Beer Misc" },
	[23] = { ["object"] = "prop_beer_patriot", ["price"] = 100, ["name"] = "Beer Misc" },
	[24] = { ["object"] = "prop_beer_logopen", ["price"] = 100, ["name"] = "Beer Misc" },
	[25] = { ["object"] = "prop_beer_logger", ["price"] = 100, ["name"] = "Beer Misc" },
	[26] = { ["object"] = "prop_beer_jakey", ["price"] = 100, ["name"] = "Beer Misc" },
	[27] = { ["object"] = "prop_beer_blr", ["price"] = 100, ["name"] = "Beer Misc" },
	[28] = { ["object"] = "prop_beer_bar", ["price"] = 100, ["name"] = "Beer Misc" },
	[29] = { ["object"] = "prop_beer_amopen", ["price"] = 100, ["name"] = "Beer Misc" },
	[30] = { ["object"] = "prop_beer_am", ["price"] = 100, ["name"] = "Beer Misc" },
	[31] = { ["object"] = "prop_beachbag_01", ["price"] = 100, ["name"] = "Beachbag Misc" },
	[32] = { ["object"] = "prop_beachbag_02", ["price"] = 100, ["name"] = "Beachbag Misc" },
	[33] = { ["object"] = "prop_beachbag_03", ["price"] = 100, ["name"] = "Beachbag Misc" },
	[34] = { ["object"] = "prop_beachbag_04", ["price"] = 100, ["name"] = "Beachbag Misc" },
	[35] = { ["object"] = "prop_beachbag_05", ["price"] = 100, ["name"] = "Beachbag Misc"},
	[36] = { ["object"] = "prop_beachbag_06", ["price"] = 100, ["name"] = "Beachbag Misc" },
	[37] = { ["object"] = "prop_bbq_1", ["price"] = 100, ["name"] = "BBQ Misc" },
	[38] = { ["object"] = "prop_bbq_2", ["price"] = 100, ["name"] = "BBQ Misc" },
	[39] = { ["object"] = "prop_bbq_3", ["price"] = 100, ["name"] = "BBQ Misc" },
	[40] = { ["object"] = "prop_bbq_4", ["price"] = 100, ["name"] = "BBQ Misc" },
	[41] = { ["object"] = "prop_bbq_4_l1", ["price"] = 100, ["name"] = "BBQ Misc" },
	[42] = { ["object"] = "prop_bbq_5", ["price"] = 100, ["name"] = "BBQ Misc" },
	[43] = { ["object"] = "prop_battery_01", ["price"] = 100, ["name"] = "Battery Misc" },
	[44] = { ["object"] = "prop_battery_02", ["price"] = 100, ["name"] = "Battery Misc" },
	[45] = { ["object"] = "prop_barbell_01", ["price"] = 100, ["name"] = "Barbell Misc" },
	[46] = { ["object"] = "prop_barbell_100kg", ["price"] = 100, ["name"] = "Barbell Misc" },
	[47] = { ["object"] = "prop_barbell_10kg", ["price"] = 100, ["name"] = "Barbell Misc" },
	[48] = { ["object"] = "prop_barbell_20kg", ["price"] = 100, ["name"] = "Barbell Misc" },
	[49] = { ["object"] = "prop_barbell_30kg", ["price"] = 100, ["name"] = "Barbell Misc" },
	[51] = { ["object"] = "prop_barbell_40kg", ["price"] = 100, ["name"] = "Barbell Misc" },
	[52] = { ["object"] = "prop_barbell_50kg", ["price"] = 100, ["name"] = "Barbell Misc" },
	[53] = { ["object"] = "prop_barbell_60kg", ["price"] = 100, ["name"] = "Barbell Misc" },
	[54] = { ["object"] = "prop_barbell_80kg", ["price"] = 100, ["name"] = "Barbell Misc" },
}
sofas = {
	[1] = { ["object"] = "miss_rub_couch_01", ["price"] = 300, ["name"] = "Old Flowered Couch" },
	[2] = { ["object"] = "prop_fib_3b_bench", ["price"] = 700, ["name"] = "3 Seat Chair" },
	[3] = { ["object"] = "prop_ld_farm_chair01", ["price"] = 250, ["name"] = "Old 1 Seat Couch" },
	[4] = { ["object"] = "prop_ld_farm_couch01", ["price"] = 300, ["name"] = "Old 3 Seat Couch" },
	[5] = { ["object"] = "prop_ld_farm_couch02", ["price"] = 300, ["name"] = "Old Striped Couch" },
	[6] = { ["object"] = "v_res_d_armchair", ["price"] = 300, ["name"] = "Old 1 Seat Couch Yellow" },
	[7] = { ["object"] = "v_res_fh_sofa", ["price"] = 3700, ["name"] = "Corner Sofa" },
	[8] = { ["object"] = "v_res_mp_sofa", ["price"] = 3700, ["name"] = "Corner Sofa 2" },
	[9] = { ["object"] = "v_res_d_sofa", ["price"] = 700, ["name"] = "Sofa 1" },
	[10] = { ["object"] = "v_res_j_sofa", ["price"] = 700, ["name"] = "Sofa 2" },
	[11] = { ["object"] = "v_res_mp_stripchair", ["price"] = 700, ["name"] = "Sofa 3" },
	[12] = { ["object"] = "v_res_m_h_sofa_sml", ["price"] = 700, ["name"] = "Sofa 4" },
	[13] = { ["object"] = "v_res_r_sofa", ["price"] = 700, ["name"] = "Sofa 5" },
	[14] = { ["object"] = "v_res_tre_sofa", ["price"] = 700, ["name"] = "Sofa 6" },
	[15] = { ["object"] = "v_res_tre_sofa_mess_a", ["price"] = 700, ["name"] = "Sofa 7" },
	[16] = { ["object"] = "v_res_tre_sofa_mess_b", ["price"] = 700, ["name"] = "Sofa 8" },
	[17] = { ["object"] = "v_res_tre_sofa_mess_c", ["price"] = 700, ["name"] = "Sofa 9" },
	[18] = { ["object"] = "v_res_tt_sofa", ["price"] = 700, ["name"] = "Sofa 10" },
	[19] = { ["object"] = "prop_rub_couch02", ["price"] = 700, ["name"] = "Sofa 11" },
}

chairs = {
	[1] = { ["object"] = "v_res_d_highchair", ["price"] = 700, ["name"] = "High Chair" },
	[2] = { ["object"] = "v_res_fa_chair01", ["price"] = 700, ["name"] = "Chair" },
	[3] = { ["object"] = "v_res_fa_chair02", ["price"] = 700, ["name"] = "Chair" },
	[4] = { ["object"] = "v_res_fh_barcchair", ["price"] = 700, ["name"] = "High Chair" },
	[5] = { ["object"] = "v_res_fh_dineeamesa", ["price"] = 700, ["name"] = "Dine Chair 1" },
	[6] = { ["object"] = "v_res_fh_dineeamesb", ["price"] = 700, ["name"] = "Dine Chair 2" },
	[7] = { ["object"] = "v_res_fh_dineeamesc", ["price"] = 700, ["name"] = "Dine Chair 3" },
	[8] = { ["object"] = "v_res_fh_easychair", ["price"] = 700, ["name"] = "Chair" },
	[9] = { ["object"] = "v_res_fh_kitnstool", ["price"] = 700, ["name"] = "Stool" },
	[10] = { ["object"] = "v_res_fh_singleseat", ["price"] = 700, ["name"] = "High Chair" },
	[11] = { ["object"] = "v_res_jarmchair", ["price"] = 700, ["name"] = "Arm Chair" },
	[12] = { ["object"] = "v_res_j_dinechair", ["price"] = 700, ["name"] = "Dining Chair" },
	[13] = { ["object"] = "v_res_j_stool", ["price"] = 700, ["name"] = "Stool" },
	[14] = { ["object"] = "v_res_mbchair", ["price"] = 700, ["name"] = "MB Chair" },
	[15] = { ["object"] = "v_res_m_armchair", ["price"] = 700, ["name"] = "Arm Chair" },
	[16] = { ["object"] = "v_res_m_dinechair", ["price"] = 700, ["name"] = "Dine Chair" },
	[17] = { ["object"] = "v_res_study_chair", ["price"] = 700, ["name"] = "Study Chair" },
	[18] = { ["object"] = "v_res_trev_framechair", ["price"] = 700, ["name"] = "Frame Chair" },
	[19] = { ["object"] = "v_res_tre_chair", ["price"] = 700, ["name"] = "Chair" },
	[20] = { ["object"] = "v_res_tre_officechair", ["price"] = 700, ["name"] = "Office Chair" },
	[21] = { ["object"] = "v_res_tre_stool", ["price"] = 700, ["name"] = "Stool" },
	[22] = { ["object"] = "v_res_tre_stool_leather", ["price"] = 700, ["name"] = "Stool Leather" },
	[23] = { ["object"] = "v_res_tre_stool_scuz", ["price"] = 700, ["name"] = "Stool Scuz" },
	[24] = { ["object"] = "v_med_p_deskchair", ["price"] = 700, ["name"] = "Desk Chair" },
	[25] = { ["object"] = "v_med_p_easychair", ["price"] = 700, ["name"] = "Easy Chair" },
	[26] = { ["object"] = "v_med_whickerchair1", ["price"] = 700, ["name"] = "Whicker Chair" },
	[27] = { ["object"] = "prop_direct_chair_01", ["price"] = 700, ["name"] = "Direct Chair 1" },
	[28] = { ["object"] = "prop_direct_chair_02", ["price"] = 700, ["name"] = "Direct Chair 2" },
	[29] = { ["object"] = "prop_yacht_lounger", ["price"] = 700, ["name"] = "Yacht Seat 1" },
	[30] = { ["object"] = "prop_yacht_seat_01", ["price"] = 700, ["name"] = "Yacht Seat 2" },
	[31] = { ["object"] = "prop_yacht_seat_02", ["price"] = 700, ["name"] = "Yacht Seat 3" },
	[32] = { ["object"] = "prop_yacht_seat_03", ["price"] = 700, ["name"] = "Yacht Seat 4" },
	[33] = { ["object"] = "v_ret_chair_white", ["price"] = 100, ["name"] = "White Chair" },
	[34] = { ["object"] = "v_ret_chair", ["price"] = 100, ["name"] = "Chair" },
	[35] = { ["object"] = "v_ret_ta_stool", ["price"] = 100, ["name"] = "TA Stool" },
	[36] = { ["object"] = "prop_cs_office_chair", ["price"] = 100, ["name"] = "Office Chair" },
}

beds = {
	[1] = { ["object"] = "v_res_d_bed", ["price"] = 700, ["name"] = "D Bed" },	
	[2] = { ["object"] = "v_res_lestersbed", ["price"] = 700, ["name"] = "L Bed" },	
	[3] = { ["object"] = "v_res_mbbed", ["price"] = 700, ["name"] = "MB Bed" },	
	[4] = { ["object"] = "v_res_mdbed", ["price"] = 700, ["name"] = "MD Bed" },	
	[5] = { ["object"] = "v_res_msonbed", ["price"] = 700, ["name"] = "Mason Bed" },	
	[6] = { ["object"] = "v_res_tre_bed1", ["price"] = 700, ["name"] = "T Bed" },	
	[7] = { ["object"] = "v_res_tre_bed2", ["price"] = 700, ["name"] = "T Bed 2" },	
	[8] = { ["object"] = "v_res_tt_bed", ["price"] = 700, ["name"] = "TT Bed" },	
}


general = {
	[1] = { ["object"] = "v_corp_facebeanbag", ["price"] = 100, ["name"] = "Bean Bag 1" },
	[2] = { ["object"] = "v_res_cherubvase", ["price"] = 2500, ["name"] = "White Vase" },
	[3] = { ["object"] = "v_res_d_paddedwall", ["price"] = 300, ["name"] = "Padded Wall" },
	[4] = { ["object"] = "v_res_d_ramskull", ["price"] = 300, ["name"] = "Item" },
	[5] = { ["object"] = "v_res_d_whips", ["price"] = 300, ["name"] = "Whips" },
	[6] = { ["object"] = "v_res_fashmag1", ["price"] = 300, ["name"] = "Mags" },
	[7] = { ["object"] = "v_res_fashmagopen", ["price"] = 300, ["name"] = "Mags Open" },
	[8] = { ["object"] = "v_res_fa_magtidy", ["price"] = 300, ["name"] = "Mag Tidy" },
	[9] = { ["object"] = "v_res_fa_yogamat002", ["price"] = 300, ["name"] = "Yoga Mat 1" },
	[10] = { ["object"] = "v_res_fa_yogamat1", ["price"] = 300, ["name"] = "Yoga Mat 2" },
	[11] = { ["object"] = "v_res_fh_aftershavebox", ["price"] = 300, ["name"] = "Aftershave" },
	[12] = { ["object"] = "v_res_fh_flowersa", ["price"] = 300, ["name"] = "Flowers" },
	[13] = { ["object"] = "v_res_fh_fruitbowl", ["price"] = 300, ["name"] = "Fruitbowl" },
	[14] = { ["object"] = "v_res_fh_laundrybasket", ["price"] = 300, ["name"] = "Laundry Basket" },
	[15] = { ["object"] = "v_res_fh_pouf", ["price"] = 300, ["name"] = "Pouf" },
	[16] = { ["object"] = "v_res_fh_sculptmod", ["price"] = 300, ["name"] = "Sculpture" },
	[17] = { ["object"] = "v_res_j_magrack", ["price"] = 300, ["name"] = "Mag Rack" },
	[18] = { ["object"] = "v_res_jewelbox", ["price"] = 300, ["name"] = "Jewel Box" },
	[19] = { ["object"] = "v_res_mbbin", ["price"] = 300, ["name"] = "Bin" },
	[20] = { ["object"] = "v_res_mbowlornate", ["price"] = 300, ["name"] = "Ornate Bowl" },
	[21] = { ["object"] = "v_res_mbronzvase", ["price"] = 300, ["name"] = "Bronze Vase" },
	[22] = { ["object"] = "v_res_mchalkbrd", ["price"] = 300, ["name"] = "Chalk Board" },
	[23] = { ["object"] = "v_res_mddresser", ["price"] = 300, ["name"] = "Dresser" },
	[24] = { ["object"] = "v_res_mplinth", ["price"] = 300, ["name"] = "Linth" },
	[25] = { ["object"] = "v_res_mp_ashtrayb", ["price"] = 300, ["name"] = "Ashtray" },
	[26] = { ["object"] = "v_res_m_candle", ["price"] = 300, ["name"] = "Candle" },
	[27] = { ["object"] = "v_res_m_candlelrg", ["price"] = 300, ["name"] = "Candle Large" },
	[28] = { ["object"] = "v_res_m_kscales", ["price"] = 300, ["name"] = "Scales" },
	[29] = { ["object"] = "v_res_tt_bedpillow", ["price"] = 300, ["name"] = "Bed Pillow" },
}

general2 = {
	[1] = { ["object"] = "prop_a4_pile_01", ["price"] = 100, ["name"] = "A4 Pile" },
	[2] = { ["object"] = "prop_amb_40oz_03", ["price"] = 100, ["name"] = "40 oz" },
	[3] = { ["object"] = "prop_amb_beer_bottle", ["price"] = 100, ["name"] = "Beer" },
	[4] = { ["object"] = "prop_aviators_01", ["price"] = 100, ["name"] = "Aviators" },
	[5] = { ["object"] = "prop_barry_table_detail", ["price"] = 100, ["name"] = "Detail" },
	[6] = { ["object"] = "prop_beer_box_01", ["price"] = 100, ["name"] = "Beers" },
	[7] = { ["object"] = "prop_binoc_01", ["price"] = 100, ["name"] = "Binoculars" },
	[8] = { ["object"] = "prop_blox_spray", ["price"] = 100, ["name"] = "Blox Spray" },
	[9] = { ["object"] = "prop_bongos_01", ["price"] = 100, ["name"] = "Bongos" },
	[10] = { ["object"] = "prop_bong_01", ["price"] = 100, ["name"] = "Bong" },
	[11] = { ["object"] = "prop_boombox_01", ["price"] = 100, ["name"] = "Boombox" },
	[12] = { ["object"] = "prop_bowl_crisps", ["price"] = 100, ["name"] = "Bowl Crisps" },
	[13] = { ["object"] = "prop_candy_pqs", ["price"] = 100, ["name"] = "Candy" },
	[14] = { ["object"] = "prop_carrier_bag_01", ["price"] = 100, ["name"] = "Carrier bag" },
	[15] = { ["object"] = "prop_ceramic_jug_01", ["price"] = 100, ["name"] = "Ceramic Jug" },
	[16] = { ["object"] = "prop_cigar_pack_01", ["price"] = 100, ["name"] = "Cigar Pack 1" },
	[17] = { ["object"] = "prop_cigar_pack_02", ["price"] = 100, ["name"] = "Cigar Pack 2" },
	[18] = { ["object"] = "prop_cs_beer_box", ["price"] = 100, ["name"] = "Beer Box 2" },
	[19] = { ["object"] = "prop_cs_binder_01", ["price"] = 100, ["name"] = "Binder" },
	[20] = { ["object"] = "prop_cs_bs_cup", ["price"] = 100, ["name"] = "Cup" },
	[21] = { ["object"] = "prop_cs_cashenvelope", ["price"] = 100, ["name"] = "Envelope" },
	[22] = { ["object"] = "prop_cs_champ_flute", ["price"] = 100, ["name"] = "Flute" },
	[23] = { ["object"] = "prop_cs_duffel_01", ["price"] = 100, ["name"] = "Duffel Bag" },
	[24] = { ["object"] = "prop_cs_dvd", ["price"] = 50, ["name"] = "DVD" },
	[25] = { ["object"] = "prop_cs_dvd_case", ["price"] = 50, ["name"] = "DVD Case" },
	[26] = { ["object"] = "prop_cs_film_reel_01", ["price"] = 100, ["name"] = "Film Reel" },
	[27] = { ["object"] = "prop_cs_ilev_blind_01", ["price"] = 100, ["name"] = "Blind" },
	[28] = { ["object"] = "p_ld_bs_bag_01", ["price"] = 100, ["name"] = "Bag" },
	[29] = { ["object"] = "prop_cs_ironing_board", ["price"] = 100, ["name"] = "Ironing Board" },
	[30] = { ["object"] = "prop_cs_katana_01", ["price"] = 100, ["name"] = "Katana" },
	[31] = { ["object"] = "prop_cs_kettle_01", ["price"] = 100, ["name"] = "Kettle" },
	[32] = { ["object"] = "prop_cs_lester_crate", ["price"] = 100, ["name"] = "Crate" },
	[33] = { ["object"] = "prop_cs_petrol_can", ["price"] = 100, ["name"] = "Petrol Can" },
	[34] = { ["object"] = "prop_cs_sack_01", ["price"] = 100, ["name"] = "Sack" },
	[35] = { ["object"] = "prop_cs_script_bottle_01", ["price"] = 100, ["name"] = "Script Bottle" },
	[36] = { ["object"] = "prop_cs_script_bottle", ["price"] = 100, ["name"] = "Script Bottle 2" },
	[37] = { ["object"] = "prop_cs_street_binbag_01", ["price"] = 100, ["name"] = "Bin Bag" },
	[38] = { ["object"] = "prop_cs_whiskey_bottle", ["price"] = 100, ["name"] = "Whiskey Bottle" },
	[39] = { ["object"] = "prop_sh_bong_01", ["price"] = 100, ["name"] = "Bong" },
	[40] = { ["object"] = "prop_peanut_bowl_01", ["price"] = 100, ["name"] = "Peanuts" },
	[41] = { ["object"] = "prop_tumbler_01", ["price"] = 100, ["name"] = "Tumbler" },

}
general3 = {
	[1] = { ["object"] = "v_ret_csr_bin", ["price"] = 100, ["name"] = "CSR Bin" },
	[2] = { ["object"] = "v_ret_fh_wickbskt", ["price"] = 100, ["name"] = "Basket" },
	[3] = { ["object"] = "v_ret_gc_bag01", ["price"] = 100, ["name"] = "GC Bag 1" },
	[4] = { ["object"] = "v_ret_gc_bag02", ["price"] = 100, ["name"] = "GC Bag 2" },
	[5] = { ["object"] = "v_ret_gc_bin", ["price"] = 100, ["name"] = "GC Bin" },
	[6] = { ["object"] = "v_ret_gc_cashreg", ["price"] = 100, ["name"] = "Cash Register" },
	[7] = { ["object"] = "v_ret_gc_chair01", ["price"] = 100, ["name"] = "GC Chair 01" },
	[8] = { ["object"] = "v_ret_gc_chair02", ["price"] = 100, ["name"] = "GC Chair 02" },
	[9] = { ["object"] = "v_ret_gc_clock", ["price"] = 100, ["name"] = "Clock" },
	[10] = { ["object"] = "v_ret_hd_prod1_", ["price"] = 100, ["name"] = "Prod 1" },
	[11] = { ["object"] = "v_ret_hd_prod2_", ["price"] = 100, ["name"] = "Prod 2" },
	[12] = { ["object"] = "v_ret_hd_prod3_", ["price"] = 100, ["name"] = "Prod 3" },
	[13] = { ["object"] = "v_ret_hd_prod4_", ["price"] = 100, ["name"] = "Prod 4" },
	[14] = { ["object"] = "v_ret_hd_prod5_", ["price"] = 100, ["name"] = "Prod 5" },
	[15] = { ["object"] = "v_ret_hd_prod6_", ["price"] = 100, ["name"] = "Prod 6" },
	[16] = { ["object"] = "v_ret_hd_unit1_", ["price"] = 100, ["name"] = "HD Unit 1" },
	[17] = { ["object"] = "v_ret_hd_unit2_", ["price"] = 100, ["name"] = "HD Unit 2" },
	[18] = { ["object"] = "v_ret_ml_fridge02", ["price"] = 100, ["name"] = "Fridge" },
	[19] = { ["object"] = "v_ret_ps_bag_01", ["price"] = 100, ["name"] = "Bag 1" },
	[20] = { ["object"] = "v_ret_ps_bag_02", ["price"] = 100, ["name"] = "Bag 2" },
	[21] = { ["object"] = "v_ret_ta_book1", ["price"] = 100, ["name"] = "Book 1" },
	[22] = { ["object"] = "v_ret_ta_book2", ["price"] = 100, ["name"] = "Book 2" },
	[23] = { ["object"] = "v_ret_ta_book3", ["price"] = 100, ["name"] = "Book 3" },
	[24] = { ["object"] = "v_ret_ta_book4", ["price"] = 100, ["name"] = "Book 4" },
	[25] = { ["object"] = "v_ret_ta_camera", ["price"] = 100, ["name"] = "Cam" },
	[26] = { ["object"] = "v_ret_ta_firstaid", ["price"] = 100, ["name"] = "First Aid" },
	[27] = { ["object"] = "v_ret_ta_hero", ["price"] = 100, ["name"] = "Hero" },
	[28] = { ["object"] = "v_ret_ta_mag1", ["price"] = 100, ["name"] = "Mag 1" },
	[29] = { ["object"] = "v_ret_ta_mag2", ["price"] = 100, ["name"] = "Mag 2" },
	[30] = { ["object"] = "v_ret_ta_skull", ["price"] = 100, ["name"] = "Skull" },
	[31] = { ["object"] = "prop_acc_guitar_01", ["price"] = 100, ["name"] = "Guitar" },
	[32] = { ["object"] = "prop_amb_handbag_01", ["price"] = 100, ["name"] = "Handbag" },
	[33] = { ["object"] = "prop_attache_case_01", ["price"] = 100, ["name"] = "Case" },
	[34] = { ["object"] = "prop_big_bag_01", ["price"] = 100, ["name"] = "Big Bag" },
	[35] = { ["object"] = "prop_bonesaw", ["price"] = 100, ["name"] = "Bonesaw" },
	[36] = { ["object"] = "prop_cs_fertilizer", ["price"] = 100, ["name"] = "Fertilizer" },
	[37] = { ["object"] = "prop_cs_shopping_bag", ["price"] = 100, ["name"] = "Shopping Bag" },
	[38] = { ["object"] = "prop_cs_vial_01", ["price"] = 100, ["name"] = "Vial" },
	[39] = { ["object"] = "prop_defilied_ragdoll_01", ["price"] = 100, ["name"] = "Ragdoll" }, 
}
general4 = {
	[1] = { ["object"] = "prop_dummy_01", ["price"] = 100, ["name"] = "Dummy" },
	[2] = { ["object"] = "prop_egg_clock_01", ["price"] = 100, ["name"] = "Egg Clock" },
	[3] = { ["object"] = "prop_el_guitar_01", ["price"] = 100, ["name"] = "E Guitar 1" },
	[4] = { ["object"] = "prop_el_guitar_02", ["price"] = 100, ["name"] = "E Guitar 2" },
	[5] = { ["object"] = "prop_el_guitar_03", ["price"] = 100, ["name"] = "E Guitar 2" },
	[6] = { ["object"] = "prop_feed_sack_01", ["price"] = 100, ["name"] = "Feed Sack" },
	[7] = { ["object"] = "prop_floor_duster_01", ["price"] = 100, ["name"] = "Floor Duster" },
	[8] = { ["object"] = "prop_fruit_basket", ["price"] = 100, ["name"] = "Fruit Basket" },
	[9] = { ["object"] = "prop_f_duster_02", ["price"] = 100, ["name"] = "Duster" },
	[10] = { ["object"] = "prop_grapes_02", ["price"] = 100, ["name"] = "Grapes" },
	[11] = { ["object"] = "prop_hotel_clock_01", ["price"] = 100, ["name"] = "Hotel Clock" },
	[12] = { ["object"] = "prop_idol_case_01", ["price"] = 100, ["name"] = "Idol Case" },
	[13] = { ["object"] = "prop_jewel_02a", ["price"] = 100, ["name"] = "Jewels" },
	[14] = { ["object"] = "prop_jewel_02b", ["price"] = 100, ["name"] = "Jewels" },
	[15] = { ["object"] = "prop_jewel_02c", ["price"] = 100, ["name"] = "Jewels" },
	[16] = { ["object"] = "prop_jewel_03a", ["price"] = 100, ["name"] = "Jewels" },
	[17] = { ["object"] = "prop_jewel_03b", ["price"] = 100, ["name"] = "Jewels" },
	[18] = { ["object"] = "prop_jewel_04a", ["price"] = 100, ["name"] = "Jewels" },
	[19] = { ["object"] = "prop_jewel_04b", ["price"] = 100, ["name"] = "Jewels" },
	[20] = { ["object"] = "prop_j_disptray_01", ["price"] = 100, ["name"] = "Display Tray" },
	[21] = { ["object"] = "prop_j_disptray_01b", ["price"] = 100, ["name"] = "Display Tray" },
	[22] = { ["object"] = "prop_j_disptray_02", ["price"] = 100, ["name"] = "Display Tray" },
	[23] = { ["object"] = "prop_j_disptray_03", ["price"] = 100, ["name"] = "Display Tray" },
	[24] = { ["object"] = "prop_j_disptray_04", ["price"] = 100, ["name"] = "Display Tray" },
	[25] = { ["object"] = "prop_j_disptray_04b", ["price"] = 100, ["name"] = "Display Tray" },
	[26] = { ["object"] = "prop_j_disptray_05", ["price"] = 100, ["name"] = "Display Tray" },
	[27] = { ["object"] = "prop_j_disptray_05b", ["price"] = 100, ["name"] = "Display Tray" },
	[28] = { ["object"] = "prop_ld_greenscreen_01", ["price"] = 100, ["name"] = "Green Screen" },
	[29] = { ["object"] = "prop_ld_handbag", ["price"] = 100, ["name"] = "Handbag" },
	[30] = { ["object"] = "prop_ld_jerrycan_01", ["price"] = 100, ["name"] = "Jerry Can" },
	[31] = { ["object"] = "prop_ld_keypad_01", ["price"] = 100, ["name"] = "Keypad 1" },
	[32] = { ["object"] = "prop_ld_keypad_01b", ["price"] = 100, ["name"] = "Keypad 2" },
	[33] = { ["object"] = "prop_ld_suitcase_01", ["price"] = 100, ["name"] = "Suitcase 1" },
	[34] = { ["object"] = "prop_ld_suitcase_02", ["price"] = 100, ["name"] = "Suitcase 2" },
	[35] = { ["object"] = "hei_p_attache_case_shut", ["price"] = 100, ["name"] = "Suitcase 3"},
	[36] = { ["object"] = "prop_mr_rasberryclean", ["price"] = 100, ["name"] = "Rasberry Clean" },
	[37] = { ["object"] = "prop_paper_bag_01", ["price"] = 100, ["name"] = "Paper Bag" },
	[38] = { ["object"] = "prop_shopping_bags01", ["price"] = 100, ["name"] = "Shopping Bags" },
	[39] = { ["object"] = "prop_shopping_bags02", ["price"] = 100, ["name"] = "Shopping Bags 2" },
	[40] = { ["object"] = "prop_yoga_mat_01", ["price"] = 100, ["name"] = "Yoga Mat 1" },
	[41] = { ["object"] = "prop_yoga_mat_02", ["price"] = 100, ["name"] = "Yoga Mat 2" },
	[42] = { ["object"] = "prop_yoga_mat_03", ["price"] = 100, ["name"] = "Yoga Mat 3" },
	[43] = { ["object"] = "p_ld_sax", ["price"] = 100, ["name"] = "Sax" },
	[44] = { ["object"] = "p_ld_soc_ball_01", ["price"] = 100, ["name"] = "SOCCER Ball" },
	[45] = { ["object"] = "p_watch_01", ["price"] = 100, ["name"] = "Watch 1" },
	[46] = { ["object"] = "p_watch_02", ["price"] = 100, ["name"] = "Watch 2" },
	[47] = { ["object"] = "p_watch_03", ["price"] = 100, ["name"] = "Watch 3" },
	[48] = { ["object"] = "p_watch_04", ["price"] = 100, ["name"] = "Watch 4" },
	[49] = { ["object"] = "p_watch_05", ["price"] = 100, ["name"] = "Watch 5" },
	[51] = { ["object"] = "p_watch_06", ["price"] = 100, ["name"] = "Watch 6" },
}

small = {
	[1] = { ["object"] = "v_res_r_figcat", ["price"] = 300, ["name"] = "Fig Cat" },
	[2] = { ["object"] = "v_res_r_figclown", ["price"] = 300, ["name"] = "Fig Clown" },
	[3] = { ["object"] = "v_res_r_figauth2", ["price"] = 300, ["name"] = "Fig Auth" },
	[4] = { ["object"] = "v_res_r_figfemale", ["price"] = 300, ["name"] = "Fig Female" },
	[5] = { ["object"] = "v_res_r_figflamenco", ["price"] = 300, ["name"] = "Fig Flamenco" },
	[6] = { ["object"] = "v_res_r_figgirl", ["price"] = 300, ["name"] = "Fig Girl" },
	[7] = { ["object"] = "v_res_r_figgirlclown", ["price"] = 300, ["name"] = "Fig Girl Clown" },
	[8] = { ["object"] = "v_res_r_figoblisk", ["price"] = 300, ["name"] = "Fig Oblisk" },
	[9] = { ["object"] = "v_res_r_figpillar", ["price"] = 300, ["name"] = "Fig Pillar" },
	[10] = { ["object"] = "v_res_r_teapot", ["price"] = 300, ["name"] = "Teapot" },
	[11] = { ["object"] = "v_res_sculpt_dec", ["price"] = 300, ["name"] = "Sculpture 1" },
	[12] = { ["object"] = "v_res_sculpt_decd", ["price"] = 300, ["name"] = "Sculpture 2" },
	[13] = { ["object"] = "v_res_sculpt_dece", ["price"] = 300, ["name"] = "Sculpture 3" },
	[14] = { ["object"] = "v_res_sculpt_decf", ["price"] = 300, ["name"] = "Sculpture 4" },
	[15] = { ["object"] = "v_res_skateboard", ["price"] = 300, ["name"] = "Skateboard" },
	[16] = { ["object"] = "v_res_sketchpad", ["price"] = 300, ["name"] = "Sketchpad" },
	[17] = { ["object"] = "v_res_tissues", ["price"] = 300, ["name"] = "Tissues" },
	[18] = { ["object"] = "v_res_tre_basketmess", ["price"] = 300, ["name"] = "Basket" },
	[19] = { ["object"] = "v_res_tre_bin", ["price"] = 300, ["name"] = "Bin" },
	[20] = { ["object"] = "v_res_tre_cushiona", ["price"] = 300, ["name"] = "Cushion 1" },
	[21] = { ["object"] = "v_res_tre_cushionb", ["price"] = 300, ["name"] = "Cushion 2" },
	[22] = { ["object"] = "v_res_tre_cushionc", ["price"] = 300, ["name"] = "Cushion 3" },
	[23] = { ["object"] = "v_res_tre_cushiond", ["price"] = 300, ["name"] = "Cushion 4" },
	[24] = { ["object"] = "v_res_tre_cushnscuzb", ["price"] = 300, ["name"] = "Cushion 5" },
	[25] = { ["object"] = "v_res_tre_cushnscuzd", ["price"] = 300, ["name"] = "Cushion 6" },
	[26] = { ["object"] = "v_res_tre_fruitbowl", ["price"] = 300, ["name"] = "Fruitbowl" },
	[27] = { ["object"] = "v_med_p_sideboard", ["price"] = 300, ["name"] = "Sideboard" },
	[28] = { ["object"] = "prop_idol_01", ["price"] = 100, ["name"] = "Idol 1" },
	

}

storage = {
	[1] = { ["object"] = "v_res_cabinet", ["price"] = 2500, ["name"] = "Cabinet Large" },
	[2] = { ["object"] = "v_res_d_dressingtable", ["price"] = 2500, ["name"] = "Dressing Table" },
	[3] = { ["object"] = "v_res_d_sideunit", ["price"] = 2500, ["name"] = "Side Unit" },
	[4] = { ["object"] = "v_res_fh_sidebrddine", ["price"] = 2500, ["name"] = "Side Unit" },
	[5] = { ["object"] = "v_res_fh_sidebrdlngb", ["price"] = 2500, ["name"] = "Side Unit" },
	[6] = { ["object"] = "v_res_mbbedtable", ["price"] = 2500, ["name"] = "Bed Unit" },
	[7] = { ["object"] = "v_res_j_tvstand", ["price"] = 2500, ["name"] = "Tv Unit" },
	[8] = { ["object"] = "v_res_mbdresser", ["price"] = 2500, ["name"] = "Dresser Unit" },
	[9] = { ["object"] = "v_res_mbottoman", ["price"] = 2500, ["name"] = "Bottoman Unit" },
	[10] = { ["object"] = "v_res_mconsolemod", ["price"] = 2500, ["name"] = "Console Unit" },
	[11] = { ["object"] = "v_res_mcupboard", ["price"] = 2500, ["name"] = "Cupboard Unit" },
	[12] = { ["object"] = "v_res_mdchest", ["price"] = 2500, ["name"] = "Chest Unit" },
	[13] = { ["object"] = "v_res_msoncabinet", ["price"] = 2500, ["name"] = "Mason Unit" },
	[14] = { ["object"] = "v_res_m_armoire", ["price"] = 2500, ["name"] = "Armoire Unit" },
	[15] = { ["object"] = "v_res_m_sidetable", ["price"] = 2500, ["name"] = "Side Unit" },
	[16] = { ["object"] = "v_res_son_desk", ["price"] = 2500, ["name"] = "Desk Unit" },
	[17] = { ["object"] = "v_res_tre_bedsidetable", ["price"] = 2500, ["name"] = "Side Unit" },
	[18] = { ["object"] = "v_res_tre_bedsidetableb", ["price"] = 2500, ["name"] = "Side Unit 2" },
	[19] = { ["object"] = "v_res_tre_smallbookshelf", ["price"] = 2500, ["name"] = "Book Unit" },
	[20] = { ["object"] = "v_res_tre_storagebox", ["price"] = 2500, ["name"] = "Box Unit" },
	[21] = { ["object"] = "v_res_tre_storageunit", ["price"] = 2500, ["name"] = "Storage Unit" },
	[22] = { ["object"] = "v_res_tre_wardrobe", ["price"] = 2500, ["name"] = "Wardrobe Unit" },
	[23] = { ["object"] = "v_res_tre_wdunitscuz", ["price"] = 2500, ["name"] = "Wood Unit" },
	[24] = { ["object"] = "prop_devin_box_closed", ["price"] = 100, ["name"] = "Bean Bag 1" },
	[25] = { ["object"] = "prop_mil_crate_01", ["price"] = 100, ["name"] = "Mil Crate 1" },
	[26] = { ["object"] = "prop_mil_crate_02", ["price"] = 100, ["name"] = "Mil Crate 2" },
	[27] = { ["object"] = "prop_ld_int_safe_01", ["price"] = 1100, ["name"] = "Safe" },
}

electronics = {
	[1] = { ["object"] = "prop_trailr_fridge", ["price"] = 300, ["name"] = "Old Fridge" },
	[2] = { ["object"] = "v_res_fh_speaker", ["price"] = 300, ["name"] = "Speaker" },
	[3] = { ["object"] = "v_res_fh_speakerdock", ["price"] = 300, ["name"] = "Speaker Dock" },
	[4] = { ["object"] = "v_res_fh_bedsideclock", ["price"] = 300, ["name"] = "Bedside Clock" },
	[5] = { ["object"] = "v_res_fa_phone", ["price"] = 300, ["name"] = "Phone" },
	[6] = { ["object"] = "v_res_fh_towerfan", ["price"] = 300, ["name"] = "Tower Fan" },
	[7] = { ["object"] = "v_res_fa_fan", ["price"] = 300, ["name"] = "Fan" },
	[8] = { ["object"] = "v_res_lest_bigscreen", ["price"] = 300, ["name"] = "Bigscreen" },
	[9] = { ["object"] = "v_res_lest_monitor", ["price"] = 300, ["name"] = "Monitor" },
	[10] = { ["object"] = "v_res_tre_mixer", ["price"] = 300, ["name"] = "Mixer" },
	[11] = { ["object"] = "prop_cs_cctv", ["price"] = 100, ["name"] = "CCTV" },
	[12] = { ["object"] = "prop_ld_lap_top", ["price"] = 100, ["name"] = "Laptop" },
	[13] = { ["object"] = "prop_ld_monitor_01", ["price"] = 100, ["name"] = "Monitor" },

}


lighting = {
	[1] = { ["object"] = "v_corp_cd_desklamp", ["price"] = 100, ["name"] = "Desk Corp Lamp" },
	[2] = { ["object"] = "v_res_desklamp", ["price"] = 100, ["name"] = "Desk Lamp" },
	[3] = { ["object"] = "v_res_d_lampa", ["price"] = 100, ["name"] = "Lamp AA" },
	[4] = { ["object"] = "v_res_fa_lamp1on", ["price"] = 100, ["name"] = "Lamp 1" },
	[5] = { ["object"] = "v_res_fh_floorlamp", ["price"] = 100, ["name"] = "Floor Lamp" },
	[6] = { ["object"] = "v_res_fh_lampa_on", ["price"] = 100, ["name"] = "Lamp 2" },
	[7] = { ["object"] = "v_res_j_tablelamp1", ["price"] = 100, ["name"] = "Table Lamp" },
	[8] = { ["object"] = "v_res_j_tablelamp2", ["price"] = 100, ["name"] = "Table Lamp 2" },
	[9] = { ["object"] = "v_res_mdbedlamp", ["price"] = 100, ["name"] = "Bed Lamp" },
	[10] = { ["object"] = "v_res_mplanttongue", ["price"] = 100, ["name"] = "Plant Tongue Lamp" },
	[11] = { ["object"] = "v_res_mtblelampmod", ["price"] = 100, ["name"] = "Table Lamp 3" },
	[12] = { ["object"] = "v_res_m_lampstand", ["price"] = 100, ["name"] = "Lamp Stand" },
	[13] = { ["object"] = "v_res_m_lampstand2", ["price"] = 100, ["name"] = "Lamp Stand 2" },
	[14] = { ["object"] = "v_res_m_lamptbl", ["price"] = 100, ["name"] = "Table Lamp 4" },
	[15] = { ["object"] = "v_res_tre_lightfan", ["price"] = 100, ["name"] = "Light Fan" },
	[16] = { ["object"] = "v_res_tre_talllamp", ["price"] = 100, ["name"] = "Tall Lamp" },
	[17] = { ["object"] = "v_ret_fh_walllighton", ["price"] = 100, ["name"] = "Wall Light" },
	[18] = { ["object"] = "v_ret_gc_lamp", ["price"] = 100, ["name"] = "GC Lamp" },

	[19] = { ["object"] = "prop_dummy_light", ["price"] = 100, ["name"] = "Flickering Light" },
	[20] = { ["object"] = "prop_ld_cont_light_01", ["price"] = 100, ["name"] = "Side Wall Light" },
	[21] = { ["object"] = "V_44_D_emis", ["price"] = 100, ["name"] = "Test Light" },



}


tables = {
	[1] = { ["object"] = "v_res_d_coffeetable", ["price"] = 500, ["name"] = "Coffee Table 1" },
	[2] = { ["object"] = "v_res_d_roundtable", ["price"] = 500, ["name"] = "Round Table" },
	[3] = { ["object"] = "v_res_d_smallsidetable", ["price"] = 500, ["name"] = "Small Side Table" },
	[4] = { ["object"] = "v_res_fh_coftablea", ["price"] = 500, ["name"] = "Table A" },
	[5] = { ["object"] = "v_res_fh_coftableb", ["price"] = 500, ["name"] = "Table B" },
	[6] = { ["object"] = "v_res_fh_coftbldisp", ["price"] = 500, ["name"] = "Table C" },
	[7] = { ["object"] = "v_res_fh_diningtable", ["price"] = 500, ["name"] = "Dining Table" },
	[8] = { ["object"] = "v_res_j_coffeetable", ["price"] = 500, ["name"] = "Coffee Table 2" },
	[9] = { ["object"] = "v_res_j_lowtable", ["price"] = 500, ["name"] = "Low Table" },
	[10] = { ["object"] = "v_res_mdbedtable", ["price"] = 500, ["name"] = "Bed Table" },
	[11] = { ["object"] = "v_res_mddesk", ["price"] = 500, ["name"] = "Desk" },
	[12] = { ["object"] = "v_res_msidetblemod", ["price"] = 500, ["name"] = "Side Table" },
	[13] = { ["object"] = "v_res_m_console", ["price"] = 500, ["name"] = "Console Table" },
	[14] = { ["object"] = "v_res_m_dinetble_replace", ["price"] = 500, ["name"] = "Dining Table 2" },
	[15] = { ["object"] = "v_res_m_h_console", ["price"] = 500, ["name"] = "Console H Table" },
	[16] = { ["object"] = "v_res_m_stool", ["price"] = 500, ["name"] = "Stool?" },
	[17] = { ["object"] = "v_res_tre_sideboard", ["price"] = 500, ["name"] = "Sideboard Table" },
	[18] = { ["object"] = "v_res_tre_table2", ["price"] = 500, ["name"] = "Table 2" },
	[19] = { ["object"] = "v_res_tre_tvstand", ["price"] = 500, ["name"] = "Tv Table" },
	[20] = { ["object"] = "v_res_tre_tvstand_tall", ["price"] = 500, ["name"] = "Tv Table Tall" },
	[21] = { ["object"] = "v_med_p_coffeetable", ["price"] = 500, ["name"] = "Med Coffee Table" },
	[22] = { ["object"] = "v_med_p_desk", ["price"] = 500, ["name"] = "Med Desk" },
	[23] = { ["object"] = "prop_yacht_table_01", ["price"] = 100, ["name"] = "Yacht Table 1" },
	[24] = { ["object"] = "prop_yacht_table_02", ["price"] = 100, ["name"] = "Yacht Table 2" },
	[25] = { ["object"] = "prop_yacht_table_03", ["price"] = 100, ["name"] = "Yacht Table 3" },
	[26] = { ["object"] = "v_ret_csr_table", ["price"] = 100, ["name"] = "CSR Table" },

}

plants = {
	[1] = { ["object"] = "prop_fib_plant_01", ["price"] = 150, ["name"] = "Plant Fib" },
	[2] = { ["object"] = "v_corp_bombplant", ["price"] = 170, ["name"] = "Plant Bomb" },		
	[3] = { ["object"] = "v_res_mflowers", ["price"] = 170, ["name"] = "Plant Flowers" },	
	[4] = { ["object"] = "v_res_mvasechinese", ["price"] = 170, ["name"] = "Plant Chinese" },	
	[5] = { ["object"] = "v_res_m_bananaplant", ["price"] = 170, ["name"] = "Plant Banana" },	
	[6] = { ["object"] = "v_res_m_palmplant1", ["price"] = 170, ["name"] = "Plant Palm" },	
	[7] = { ["object"] = "v_res_m_palmstairs", ["price"] = 170, ["name"] = "Plant Palm 2" },	
	[8] = { ["object"] = "v_res_m_urn", ["price"] = 170, ["name"] = "Plant Urn" },	
	[9] = { ["object"] = "v_res_rubberplant", ["price"] = 170, ["name"] = "Plant Rubber" },	
	[10] = { ["object"] = "v_res_tre_plant", ["price"] = 170, ["name"] = "Plant" },	
	[11] = { ["object"] = "v_res_tre_tree", ["price"] = 170, ["name"] = "Plant Tree" },	
	[12] = { ["object"] = "v_med_p_planter", ["price"] = 170, ["name"] = "Planter" },	
	[13] = { ["object"] = "v_ret_flowers", ["price"] = 100, ["name"] = "Flowers" },
	[14] = { ["object"] = "v_ret_j_flowerdisp", ["price"] = 100, ["name"] = "Flowers 1" },
	[15] = { ["object"] = "v_ret_j_flowerdisp_white", ["price"] = 100, ["name"] = "Flowers 2" },
}

kitchen = {
	[1] = { ["object"] = "prop_washer_01", ["price"] = 150, ["name"] = "Washer 1" },
	[2] = { ["object"] = "prop_washer_02", ["price"] = 150, ["name"] = "Washer 2" },
	[3] = { ["object"] = "prop_washer_03", ["price"] = 150, ["name"] = "Washer 3" },
	[4] = { ["object"] = "prop_washing_basket_01", ["price"] = 150, ["name"] = "Washing Basket" },
	[5] = { ["object"] = "v_res_fridgemoda", ["price"] = 150, ["name"] = "Fridge 1" },
	[6] = { ["object"] = "v_res_fridgemodsml", ["price"] = 150, ["name"] = "Fridge 2" },
	[7] = { ["object"] = "prop_fridge_01", ["price"] = 150, ["name"] = "Fridge 3" },
	[8] = { ["object"] = "prop_fridge_03", ["price"] = 150, ["name"] = "Fridge 4" },
	[9] = { ["object"] = "prop_cooker_03", ["price"] = 150, ["name"] = "Cooker" },
	[10] = { ["object"] = "prop_micro_01", ["price"] = 150, ["name"] = "Microwave 1" },
	[11] = { ["object"] = "prop_micro_02", ["price"] = 150, ["name"] = "Microwave 2" },
	[12] = { ["object"] = "prop_wok", ["price"] = 150, ["name"] = "Wok" },
	[13] = { ["object"] = "v_res_cakedome", ["price"] = 150, ["name"] = "Cake Plate" },
	[14] = { ["object"] = "v_res_fa_chopbrd", ["price"] = 150, ["name"] = "Chopping Board" },
	[15] = { ["object"] = "v_res_mutensils", ["price"] = 150, ["name"] = "Utensils" },
	[16] = { ["object"] = "v_res_pestle", ["price"] = 150, ["name"] = "Pestle" },
	[17] = { ["object"] = "v_ret_ta_paproll", ["price"] = 150, ["name"] = "PaperRoll 1" },
	[18] = { ["object"] = "v_ret_ta_paproll2", ["price"] = 150, ["name"] = "PaperRoll 2" },
	[19] = { ["object"] = "v_ret_fh_pot01", ["price"] = 150, ["name"] = "Pot 1" },
	[20] = { ["object"] = "v_ret_fh_pot02", ["price"] = 150, ["name"] = "Pot 2" },
	[21] = { ["object"] = "v_ret_fh_pot05", ["price"] = 150, ["name"] = "Pot 3" },
	[22] = { ["object"] = "prop_pot_03", ["price"] = 150, ["name"] = "Pot 4" },
	[23] = { ["object"] = "prop_pot_04", ["price"] = 150, ["name"] = "Pot 5" },
	[24] = { ["object"] = "prop_pot_05", ["price"] = 150, ["name"] = "Pot 6" },
	[25] = { ["object"] = "prop_pot_06", ["price"] = 150, ["name"] = "Pot 7" },
	[26] = { ["object"] = "prop_pot_rack", ["price"] = 150, ["name"] = "Pot Rack" },
	[27] = { ["object"] = "prop_kitch_juicer", ["price"] = 150, ["name"] = "Juicer" },

}


bathroom = {
	[1] = { ["object"] = "prop_ld_toilet_01", ["price"] = 100, ["name"] = "Toilet 1" },
	[2] = { ["object"] = "prop_toilet_01", ["price"] = 100, ["name"] = "Toilet 2" },
	[3] = { ["object"] = "prop_toilet_02", ["price"] = 100, ["name"] = "Toilet 3" },
	[4] = { ["object"] = "prop_sink_02", ["price"] = 100, ["name"] = "Sink 1" },
	[5] = { ["object"] = "prop_sink_04", ["price"] = 100, ["name"] = "Sink 2" },
	[6] = { ["object"] = "prop_sink_05", ["price"] = 100, ["name"] = "Sink 3" },
	[7] = { ["object"] = "prop_sink_06", ["price"] = 100, ["name"] = "Sink 4" },
	[8] = { ["object"] = "prop_soap_disp_01", ["price"] = 100, ["name"] = "Soap Dispenser" },
	[9] = { ["object"] = "prop_shower_rack_01", ["price"] = 100, ["name"] = "Shower Rack" },
	[10] = { ["object"] = "prop_handdry_01", ["price"] = 100, ["name"] = "Hand Dryer 1" },
	[11] = { ["object"] = "prop_handdry_02", ["price"] = 100, ["name"] = "Hand Dryer 2" },
	[12] = { ["object"] = "prop_towel_rail_01", ["price"] = 100, ["name"] = "Towel Rail 1" },
	[13] = { ["object"] = "prop_towel_rail_02", ["price"] = 100, ["name"] = "Towel Rail 2" },
	[14] = { ["object"] = "prop_towel_01", ["price"] = 100, ["name"] = "Towel 1" },
	[15] = { ["object"] = "v_res_mbtowel", ["price"] = 100, ["name"] = "Towel 2" },
	[16] = { ["object"] = "v_res_mbtowelfld", ["price"] = 100, ["name"] = "Towel 3" },
	[17] = { ["object"] = "v_res_mbath", ["price"] = 100, ["name"] = "Bath" },
	[18] = { ["object"] = "v_res_mbsink", ["price"] = 100, ["name"] = "Sink" },

}

medical = {
	[1] = { ["object"] = "v_med_barrel", ["price"] = 750, ["name"] = "Barrel" },
	[2] = { ["object"] = "v_med_apecrate", ["price"] = 750, ["name"] = "Ape Crate" },
	[3] = { ["object"] = "v_med_apecratelrg", ["price"] = 750, ["name"] = "Ape Crate Large" },
	[4] = { ["object"] = "v_med_bed1", ["price"] = 750, ["name"] = "Bed 1" },
	[5] = { ["object"] = "v_med_bed2", ["price"] = 750, ["name"] = "Bed 2" },
	[6] = { ["object"] = "v_med_bedtable", ["price"] = 750, ["name"] = "Bed Table" },
	[7] = { ["object"] = "v_med_bench1", ["price"] = 750, ["name"] = "Bench 1" },
	[8] = { ["object"] = "v_med_bench2", ["price"] = 750, ["name"] = "Bench 2" },
	[9] = { ["object"] = "v_med_benchcentr", ["price"] = 750, ["name"] = "Bench Center" },
	[10] = { ["object"] = "v_med_benchset1", ["price"] = 750, ["name"] = "Bench Set" },
	[11] = { ["object"] = "v_med_bigtable", ["price"] = 750, ["name"] = "Big Table" },
	[12] = { ["object"] = "v_med_bin", ["price"] = 150, ["name"] = "Bin" },
	[13] = { ["object"] = "v_med_centrifuge1", ["price"] = 750, ["name"] = "Centrifuge" },
	[14] = { ["object"] = "v_med_cooler", ["price"] = 750, ["name"] = "Cooler" },
	[15] = { ["object"] = "v_med_cor_ceilingmonitor", ["price"] = 750, ["name"] = "Monitor" },
	[16] = { ["object"] = "v_med_cor_autopsytbl", ["price"] = 750, ["name"] = "Autopsy Table" },
	[17] = { ["object"] = "v_med_cor_cembin", ["price"] = 750, ["name"] = "Bin" },
	[18] = { ["object"] = "v_med_cor_cemtrolly2", ["price"] = 750, ["name"] = "Trolley" },
	[19] = { ["object"] = "v_med_cor_chemical", ["price"] = 750, ["name"] = "Chem" },
	[20] = { ["object"] = "v_med_cor_emblmtable", ["price"] = 750, ["name"] = "BLM Table" },
	[21] = { ["object"] = "v_med_cor_fileboxa", ["price"] = 750, ["name"] = "File Box" },
	[22] = { ["object"] = "v_med_cor_filingcab", ["price"] = 750, ["name"] = "File Cab" },
	[23] = { ["object"] = "v_med_cor_hose", ["price"] = 750, ["name"] = "Hose" },
	[24] = { ["object"] = "v_med_cor_largecupboard", ["price"] = 750, ["name"] = "Large Cupboard" },
	[25] = { ["object"] = "v_med_cor_lightbox", ["price"] = 750, ["name"] = "Lightbox" },
	[26] = { ["object"] = "v_med_cor_medstool", ["price"] = 750, ["name"] = "Medstool" },
	[27] = { ["object"] = "v_med_cor_minifridge", ["price"] = 750, ["name"] = "Minifridge" },
	[28] = { ["object"] = "v_med_cor_papertowels", ["price"] = 750, ["name"] = "Papertowels" },
	[29] = { ["object"] = "v_med_cor_photocopy", ["price"] = 750, ["name"] = "Photocopy" },
	[30] = { ["object"] = "v_med_cor_tvstand", ["price"] = 750, ["name"] = "TV Stand" },
	[31] = { ["object"] = "v_med_cor_wallunita", ["price"] = 750, ["name"] = "Wall Unit" },
	[32] = { ["object"] = "v_med_examlight", ["price"] = 750, ["name"] = "Exam light" },
	[33] = { ["object"] = "v_med_gastank", ["price"] = 750, ["name"] = "Gas Tank" },
	[34] = { ["object"] = "v_med_hazmatscan", ["price"] = 750, ["name"] = "Hazmat Scan" },
	[35] = { ["object"] = "v_med_hospheadwall1", ["price"] = 750, ["name"] = "Head Wall" },
	[36] = { ["object"] = "v_med_hospseating1", ["price"] = 750, ["name"] = "Seating" },
	[37] = { ["object"] = "v_med_hosptable", ["price"] = 750, ["name"] = "Hosp Table" },
	[38] = { ["object"] = "v_med_latexgloveboxblue", ["price"] = 50, ["name"] = "Glove Box" },
	[39] = { ["object"] = "v_med_medwastebin", ["price"] = 750, ["name"] = "Wastebin" },
	[40] = { ["object"] = "v_med_oscillator3", ["price"] = 750, ["name"] = "Oscillator" },
	[41] = { ["object"] = "prop_ld_health_pack", ["price"] = 100, ["name"] = "Health Pack" },
}
